plugins { id 'com.android.application' }

android {
    namespace 'com.amb8657.websitebuilder'
    compileSdk 35
    defaultConfig {
        applicationId 'com.amb8657.websitebuilder'
        minSdk 23
        targetSdk 35
        versionCode (project.findProperty('versionCode') ?: '2').toInteger()
        versionName (project.findProperty('versionName') ?: '1.0.1')
    }
    buildTypes {
        debug {
            // Android Gradle Plugin automatically uses the standard debug keystore.
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
