package com.amb8657.websitebuilder;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import android.util.Base64;
import java.util.*;

public class BuilderV2Activity extends Activity {
 static final int PICK_IMAGE=41;
 final int BG=Color.rgb(19,18,23),SOFT=Color.rgb(30,29,35),WHITE=Color.WHITE,DIM=Color.rgb(150,148,160),ACCENT=Color.rgb(75,92,255);
 LinearLayout root,pagesBar,toolsBar,canvasHost; SharedPreferences sp; ArrayList<Project> projects=new ArrayList<>(); Project project; Page page; Block selected,imageTarget;
 static class Project{String name;ArrayList<Page> pages=new ArrayList<>();Project(String n){name=n;}}
 static class Page{String name;int bg=Color.WHITE;ArrayList<Block> blocks=new ArrayList<>();Page(String n){name=n;}}
 static class Block{String type,text,uri="",action="None",target="";int x=24,y=24,w=300,h=80,bg=Color.TRANSPARENT,tc=Color.DKGRAY,font=18;float opacity=1,radius=0;Block(String t,String s){type=t;text=s;}}
 interface ColorDone{void done(int c);}
 int dp(float n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);b.setMinHeight(0);b.setMinWidth(0);b.setTextColor(Color.DKGRAY);b.setBackground(shape(Color.WHITE,10));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("builder_v2",0);load();dashboard();}
 String enc(String s){return Base64.encodeToString(s.getBytes(),Base64.NO_WRAP|Base64.URL_SAFE);} String dec(String s){try{return new String(Base64.decode(s,Base64.NO_WRAP|Base64.URL_SAFE));}catch(Exception e){return s;}}
 void load(){String s=sp.getString("projects","");for(String n:s.split("\\|"))if(!n.isEmpty())projects.add(new Project(dec(n)));for(Project p:projects){String k="p"+enc(p.name);int pc=sp.getInt(k+"c",1);for(int i=0;i<pc;i++)p.pages.add(new Page(sp.getString(k+"n"+i,"Home")));if(p.pages.isEmpty())p.pages.add(new Page("Home"));}}
 void save(){StringBuilder names=new StringBuilder();for(Project p:projects){if(names.length()>0)names.append('|');names.append(enc(p.name));String k="p"+enc(p.name);SharedPreferences.Editor e=sp.edit().putInt(k+"c",p.pages.size());for(int i=0;i<p.pages.size();i++)e.putString(k+"n"+i,p.pages.get(i).name);e.apply();}sp.edit().putString("projects",names.toString()).apply();}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);}
 void dashboard(){base();LinearLayout h=new LinearLayout(this);h.setPadding(dp(18),dp(15),dp(18),dp(8));TextView logo=tv("M",25,WHITE);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.DEFAULT_BOLD);logo.setBackground(shape(ACCENT,12));h.addView(logo,new LinearLayout.LayoutParams(dp(46),dp(46)));TextView title=tv("  MAHA Builder",21,WHITE);title.setTypeface(Typeface.DEFAULT_BOLD);h.addView(title,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(h,new LinearLayout.LayoutParams(-1,dp(68)));TextView mw=tv("My Websites",19,WHITE);mw.setPadding(dp(18),0,0,0);root.addView(mw,new LinearLayout.LayoutParams(-1,dp(45)));ScrollView sv=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(16),dp(8),dp(16),dp(24));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));Button add=btn("+  New Website");add.setTextColor(WHITE);add.setBackground(shape(ACCENT,12));list.addView(add,new LinearLayout.LayoutParams(-1,dp(58)));add.setOnClickListener(v->createWebsite());for(Project p:projects){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(5),dp(5),dp(5));r.setBackground(shape(SOFT,12));TextView n=tv(p.name,16,WHITE);n.setTypeface(Typeface.DEFAULT_BOLD);r.addView(n,new LinearLayout.LayoutParams(0,dp(60),1));Button menu=btn("⋮");menu.setTextColor(WHITE);r.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(44)));list.addView(r,new LinearLayout.LayoutParams(-1,dp(72)));r.setOnClickListener(v->overview(p));menu.setOnClickListener(v->projectMenu(p));}}
 void projectMenu(Project p){new AlertDialog.Builder(this).setItems(new String[]{"Open","Rename","Delete"},(d,w)->{if(w==0)overview(p);else if(w==1)rename(p);else delete(p);}).show();}
 void rename(Project p){EditText e=input("Website name",p.name);new AlertDialog.Builder(this).setTitle("Rename website").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{if(!e.getText().toString().trim().isEmpty()){p.name=e.getText().toString().trim();save();dashboard();}}).show();}
 void delete(Project p){new AlertDialog.Builder(this).setTitle("Delete website?").setMessage("This removes the project from this device.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{projects.remove(p);sp.edit().clear().apply();save();dashboard();}).show();}
 void createWebsite(){base();top("Create a Website",()->dashboard());LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(20),dp(18),dp(18));root.addView(c,new LinearLayout.LayoutParams(-1,0,1));Button s=choice("＋  Start from Scratch\n    Blank canvas. Full freedom.");c.addView(s,new LinearLayout.LayoutParams(-1,dp(105)));s.setOnClickListener(v->newProject());Button t=choice("▧  Use a Template\n    Start with a ready-made layout.");c.addView(t,new LinearLayout.LayoutParams(-1,dp(105)));t.setOnClickListener(v->newProject());TextView p=tv("Popular Templates",17,WHITE);p.setPadding(0,dp(20),0,dp(8));c.addView(p);c.addView(tv("Business     Portfolio     Landing Page",14,DIM),new LinearLayout.LayoutParams(-1,dp(45)));}
 Button choice(String s){Button b=btn(s);b.setTextColor(WHITE);b.setTextSize(15);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setBackground(shape(SOFT,14));return b;}
 void newProject(){EditText e=input("Website name","My Website");new AlertDialog.Builder(this).setTitle("Name your website").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="My Website";project=new Project(n);project.pages.add(new Page("Home"));projects.add(0,project);save();page=project.pages.get(0);editor();}).show();}
 void overview(Project p){base();top(p.name,()->dashboard());LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),0);root.addView(c,new LinearLayout.LayoutParams(-1,0,1));TextView h=tv("Website overview",24,WHITE);h.setTypeface(Typeface.DEFAULT_BOLD);c.addView(h,new LinearLayout.LayoutParams(-1,dp(52)));c.addView(tv(p.pages.size()+" page(s) • saved on this device",14,DIM),new LinearLayout.LayoutParams(-1,dp(40)));Button edit=btn("Edit Website");edit.setTextColor(WHITE);edit.setBackground(shape(ACCENT,10));c.addView(edit,new LinearLayout.LayoutParams(-1,dp(55)));edit.setOnClickListener(v->{project=p;page=p.pages.get(0);editor();});Button pages=btn("Manage Pages");c.addView(pages,new LinearLayout.LayoutParams(-1,dp(55)));pages.setOnClickListener(v->{project=p;pageManager();});}
 void top(String s,Runnable back){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(8),dp(8),dp(10),dp(6));Button b=btn("‹");h.addView(b,new LinearLayout.LayoutParams(dp(48),dp(46)));TextView t=tv(s,19,WHITE);t.setTypeface(Typeface.DEFAULT_BOLD);h.addView(t,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(h,new LinearLayout.LayoutParams(-1,dp(64)));b.setOnClickListener(v->back.run());}
 void editor(){base();LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(7),dp(6),dp(7),dp(5));Button back=btn("‹");h.addView(back,new LinearLayout.LayoutParams(dp(42),dp(46)));TextView t=tv(project.name,17,WHITE);t.setTypeface(Typeface.DEFAULT_BOLD);h.addView(t,new LinearLayout.LayoutParams(0,dp(46),1));Button pre=btn("Preview"),saveb=btn("Save"),pub=btn("Publish");pre.setTextColor(WHITE);saveb.setTextColor(WHITE);pub.setTextColor(WHITE);pub.setBackground(shape(ACCENT,8));h.addView(pre,new LinearLayout.LayoutParams(dp(78),dp(44)));h.addView(saveb,new LinearLayout.LayoutParams(dp(62),dp(44)));h.addView(pub,new LinearLayout.LayoutParams(dp(75),dp(44)));root.addView(h,new LinearLayout.LayoutParams(-1,dp(60)));back.setOnClickListener(v->{save();overview(project);});saveb.setOnClickListener(v->{save();Toast.makeText(this,"Saved",Toast.LENGTH_SHORT).show();});pre.setOnClickListener(v->preview());pub.setOnClickListener(v->preview());
  HorizontalScrollView ph=new HorizontalScrollView(this);pagesBar=new LinearLayout(this);pagesBar.setPadding(dp(8),dp(4),dp(8),dp(4));ph.addView(pagesBar);root.addView(ph,new LinearLayout.LayoutParams(-1,dp(50)));HorizontalScrollView th=new HorizontalScrollView(this);toolsBar=new LinearLayout(this);toolsBar.setPadding(dp(8),dp(4),dp(8),dp(4));th.addView(toolsBar);root.addView(th,new LinearLayout.LayoutParams(-1,dp(52)));ScrollView sv=new ScrollView(this);canvasHost=new LinearLayout(this);canvasHost.setPadding(dp(10),dp(8),dp(10),dp(80));sv.addView(canvasHost);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bottom=new LinearLayout(this);bottom.setBackgroundColor(SOFT);Button p=btn("Pages"),style=btn("Style"),pv=btn("Preview");bottom.addView(p,new LinearLayout.LayoutParams(0,dp(54),1));bottom.addView(style,new LinearLayout.LayoutParams(0,dp(54),1));bottom.addView(pv,new LinearLayout.LayoutParams(0,dp(54),1));root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(64)));p.setOnClickListener(v->pageManager());style.setOnClickListener(v->pageStyle());pv.setOnClickListener(v->preview());render();}
 void render(){pagesBar.removeAllViews();for(Page q:project.pages){Button b=btn(q.name);b.setTextColor(q==page?WHITE:Color.DKGRAY);if(q==page)b.setBackground(shape(Color.rgb(55,43,92),8));b.setOnClickListener(v->{page=q;selected=null;render();});pagesBar.addView(b,new LinearLayout.LayoutParams(dp(105),dp(40)));}Button np=btn("＋ New");np.setOnClickListener(v->newPage());pagesBar.addView(np,new LinearLayout.LayoutParams(dp(90),dp(40)));toolsBar.removeAllViews();for(String s:new String[]{"Text","Image","Button","Section","Spacer","Shape","Tool"}){Button b=btn("＋ "+s);b.setOnClickListener(v->add(s));toolsBar.addView(b,new LinearLayout.LayoutParams(dp(90),dp(40)));}canvasHost.removeAllViews();FrameLayout canvas=new FrameLayout(this);canvas.setBackgroundColor(page.bg);int height=dp(650);for(Block b:page.blocks)height=Math.max(height,dp(b.y+b.h+300));canvasHost.addView(canvas,new LinearLayout.LayoutParams(-1,height));for(Block b:page.blocks)put(canvas,b);}
 void put(FrameLayout canvas,Block b){FrameLayout holder=new FrameLayout(this);holder.setX(dp(b.x));holder.setY(dp(b.y));GradientDrawable g=shape(b.bg,b.radius);if(selected==b)g.setStroke(dp(2),ACCENT);holder.setBackground(g);holder.setClipToOutline(true);holder.setAlpha(b.opacity);View v;if(b.type.equals("Image")&&!b.uri.isEmpty()){ImageView im=new ImageView(this);im.setImageURI(Uri.parse(b.uri));im.setScaleType(ImageView.ScaleType.CENTER_CROP);v=im;}else{TextView z=tv(b.text,b.font,b.tc);z.setPadding(dp(8),dp(4),dp(8),dp(4));z.setGravity(b.type.equals("Button")?Gravity.CENTER:Gravity.CENTER_VERTICAL);if(b.type.equals("Heading"))z.setTypeface(Typeface.DEFAULT_BOLD);if(b.type.equals("Button")){z.setTextColor(WHITE);z.setBackground(shape(b.bg==Color.TRANSPARENT?ACCENT:b.bg,b.radius));}if(b.type.equals("Section")||b.type.equals("Spacer")||b.type.equals("Shape"))z.setText("");v=z;}holder.addView(v,new FrameLayout.LayoutParams(-1,-1));if(selected==b){handle(holder,Gravity.LEFT|Gravity.TOP,b);handle(holder,Gravity.RIGHT|Gravity.TOP,b);handle(holder,Gravity.LEFT|Gravity.BOTTOM,b);handle(holder,Gravity.RIGHT|Gravity.BOTTOM,b);}holder.setOnTouchListener((view,e)->move(view,e,b));canvas.addView(holder,new FrameLayout.LayoutParams(dp(Math.max(60,b.w)),dp(Math.max(40,b.h))));}
 void handle(FrameLayout h,int gravity,Block b){TextView x=tv("",1,ACCENT);x.setBackground(shape(WHITE,8));h.addView(x,new FrameLayout.LayoutParams(dp(16),dp(16),gravity));x.setOnTouchListener((v,e)->resize(e,h,b,gravity));}
 boolean move(View v,MotionEvent e,Block b){if(e.getAction()==MotionEvent.ACTION_DOWN){v.setTag(new float[]{e.getRawX(),e.getRawY(),b.x,b.y});return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float[] a=(float[])v.getTag();float d=getResources().getDisplayMetrics().density;b.x=Math.max(0,(int)(a[2]+(e.getRawX()-a[0])/d));b.y=Math.max(0,(int)(a[3]+(e.getRawY()-a[1])/d));v.setX(dp(b.x));v.setY(dp(b.y));return true;}if(e.getAction()==MotionEvent.ACTION_UP){selected=b;save();render();showProperties(b);return true;}return true;}
 boolean resize(MotionEvent e,View v,Block b,int gravity){if(e.getAction()==MotionEvent.ACTION_DOWN){v.setTag(new float[]{e.getRawX(),e.getRawY(),b.w,b.h,b.x,b.y});return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float[] a=(float[])v.getTag();float d=getResources().getDisplayMetrics().density,dx=(e.getRawX()-a[0])/d,dy=(e.getRawY()-a[1])/d;int nw=Math.max(60,(int)a[2]+(int)(((gravity&Gravity.RIGHT)!=0)?dx:-dx));int nh=Math.max(40,(int)a[3]+(int)(((gravity&Gravity.BOTTOM)!=0)?dy:-dy));if((gravity&Gravity.LEFT)!=0)b.x=Math.max(0,(int)a[4]+(int)dx);if((gravity&Gravity.TOP)!=0)b.y=Math.max(0,(int)a[5]+(int)dy);b.w=nw;b.h=nh;v.setX(dp(b.x));v.setY(dp(b.y));v.getLayoutParams().width=dp(nw);v.getLayoutParams().height=dp(nh);v.requestLayout();return true;}if(e.getAction()==MotionEvent.ACTION_UP){save();render();return true;}return true;}
 void add(String type){String s=type.equals("Text")?"Write your text here.":type.equals("Heading")?"Build Something Amazing":type.equals("Button")?"Get Started":"";Block b=new Block(type,s);for(Block q:page.blocks)b.y=Math.max(b.y,q.y+q.h+24);b.w=300;b.h=type.equals("Heading")?90:type.equals("Image")?190:type.equals("Section")?180:type.equals("Spacer")?60:80;page.blocks.add(b);selected=b;save();render();if(type.equals("Image"))pick(b);else showProperties(b);}
 EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(WHITE);e.setHintTextColor(DIM);e.setSingleLine();e.setBackground(shape(Color.rgb(23,22,27),8));e.setPadding(dp(10),0,dp(10),0);return e;}
 void showProperties(Block b){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(10),dp(18),dp(10));box.addView(tv(b.type+" Properties",18,WHITE),new LinearLayout.LayoutParams(-1,dp(42)));EditText text=input("Content",b.text);box.addView(text,new LinearLayout.LayoutParams(-1,dp(50)));EditText font=input("Font size",String.valueOf(b.font));box.addView(font,new LinearLayout.LayoutParams(-1,dp(48)));Button colour=btn("Choose text colour");box.addView(colour);colour.setOnClickListener(v->picker(c->{b.tc=c;colour.setText("Text colour selected");}));EditText w=input("Width",String.valueOf(b.w)),h=input("Height",String.valueOf(b.h));LinearLayout wh=new LinearLayout(this);wh.addView(w,new LinearLayout.LayoutParams(0,dp(48),1));wh.addView(h,new LinearLayout.LayoutParams(0,dp(48),1));box.addView(wh);SeekBar op=new SeekBar(this);op.setMax(100);op.setProgress((int)(b.opacity*100));box.addView(tv("Opacity",12,DIM));box.addView(op,new LinearLayout.LayoutParams(-1,dp(42)));op.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){b.opacity=p/100f;}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
  if(b.type.equals("Image")){Button im=btn("Replace image / Crop / Fit");box.addView(im);im.setOnClickListener(v->pick(b));Button rad=btn("Corner radius / Circle");box.addView(rad);rad.setOnClickListener(v->radius(b));}if(b.type.equals("Button")){Button ac=btn("Action: "+b.action);box.addView(ac);ac.setOnClickListener(v->actions(b));}if(b.type.equals("Text")||b.type.equals("Heading")||b.type.equals("Image")||b.type.equals("Button")){Button an=btn("Animation / Interaction");box.addView(an);an.setOnClickListener(v->animation(b));}
  LinearLayout r=new LinearLayout(this);Button del=btn("Delete"),close=btn("Close"),apply=btn("Apply");r.addView(del,new LinearLayout.LayoutParams(0,dp(46),1));r.addView(close,new LinearLayout.LayoutParams(0,dp(46),1));apply.setTextColor(WHITE);apply.setBackground(shape(ACCENT,8));r.addView(apply,new LinearLayout.LayoutParams(0,dp(46),1));box.addView(r);final Dialog d=new Dialog(this);d.setContentView(box);del.setOnClickListener(v->{page.blocks.remove(b);selected=null;save();d.dismiss();render();});close.setOnClickListener(v->d.dismiss());apply.setOnClickListener(v->{b.text=text.getText().toString();try{b.font=Math.max(8,Integer.parseInt(font.getText().toString()));}catch(Exception e){}try{b.w=Math.max(60,Integer.parseInt(w.getText().toString()));b.h=Math.max(40,Integer.parseInt(h.getText().toString()));}catch(Exception e){}save();d.dismiss();render();});d.show();Window win=d.getWindow();if(win!=null){win.setBackgroundDrawable(shape(SOFT,18));win.setGravity(Gravity.BOTTOM);win.setLayout(-1,WindowManager.LayoutParams.WRAP_CONTENT);}}
 void picker(final ColorDone done){int[] cs={Color.BLACK,Color.WHITE,ACCENT,Color.RED,Color.GREEN,Color.BLUE,Color.YELLOW,Color.GRAY};LinearLayout r=new LinearLayout(this);r.setPadding(dp(14),dp(14),dp(14),dp(14));final Dialog d=new AlertDialog.Builder(this).setTitle("Choose a colour").setView(r).create();for(int c:cs){Button x=new Button(this);x.setBackground(shape(c,20));r.addView(x,new LinearLayout.LayoutParams(dp(42),dp(42)));x.setOnClickListener(v->{done.done(c);d.dismiss();});}d.show();}
 void radius(Block b){SeekBar s=new SeekBar(this);s.setMax(50);s.setProgress((int)b.radius);new AlertDialog.Builder(this).setTitle("Corner radius").setMessage("50 gives a circular look when width and height match.").setView(s).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{b.radius=s.getProgress();save();render();}).show();}
 void pick(Block b){imageTarget=b;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_IMAGE);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK_IMAGE&&c==RESULT_OK&&d!=null&&imageTarget!=null){imageTarget.uri=d.getData().toString();save();render();showProperties(imageTarget);}}
 void actions(Block b){String[] a={"Open Page","Open Website","Email","Phone","Scroll to Section","Show / Hide","Animation","Back"};new AlertDialog.Builder(this).setTitle("Button Action").setItems(a,(d,w)->{b.action=a[w];if(w==0)pageTarget(b);else if(w==1)target(b,"Website URL","https://");else if(w==2)target(b,"Email address","");else if(w==3)target(b,"Phone number","");else if(w==4)target(b,"Section name","");else if(w==5)elementTarget(b);else if(w==6)animation(b);else{b.target="";save();}}).show();}
 void pageTarget(Block b){ArrayList<String> n=new ArrayList<>();for(Page p:project.pages)n.add(p.name);n.add("＋ Create New Page");new AlertDialog.Builder(this).setTitle("Select destination page").setItems(n.toArray(new String[0]),(d,w)->{if(w==project.pages.size()){newPage();}else{b.target=project.pages.get(w).name;save();}}).show();}
 void target(Block b,String title,String hint){EditText e=input(title,hint);new AlertDialog.Builder(this).setTitle(b.action).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{b.target=e.getText().toString();save();}).show();}
 void elementTarget(Block b){ArrayList<String> n=new ArrayList<>();for(int i=0;i<page.blocks.size();i++)if(page.blocks.get(i)!=b)n.add(i+" • "+page.blocks.get(i).type);new AlertDialog.Builder(this).setTitle("Select element").setItems(n.toArray(new String[0]),(d,w)->{b.target=n.get(w);save();}).show();}
 void animation(Block b){String[] a={"Fade In","Fade Out","Slide In","Scale In","Rotate","Bounce","None"};new AlertDialog.Builder(this).setTitle("Animation").setItems(a,(d,w)->{b.action="Animation: "+a[w];save();}).show();}
 void newPage(){EditText e=input("Page name","");new AlertDialog.Builder(this).setTitle("Create New Page").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="New Page";page=new Page(n);project.pages.add(page);selected=null;save();render();}).show();}
 void pageManager(){ArrayList<String> n=new ArrayList<>();for(Page p:project.pages)n.add(p.name);n.add("＋ New Page");new AlertDialog.Builder(this).setTitle("Pages").setItems(n.toArray(new String[0]),(d,w)->{if(w==project.pages.size())newPage();else{page=project.pages.get(w);selected=null;render();}}).show();}
 void pageStyle(){String[] n={"White","Soft Gray","Black","Purple Tint"};new AlertDialog.Builder(this).setTitle("Page background").setItems(n,(d,w)->{page.bg=new int[]{Color.WHITE,Color.rgb(245,245,248),Color.rgb(20,20,24),Color.rgb(247,244,255)}[w];save();render();}).show();}
 void preview(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.addView(tv("Live Preview",18,WHITE),new LinearLayout.LayoutParams(-1,dp(52)));ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundColor(page.bg);for(Block b:page.blocks){TextView t=tv(b.type.equals("Image")?"Image":b.text,b.font,b.tc);t.setPadding(dp(12),dp(10),dp(12),dp(10));c.addView(t,new LinearLayout.LayoutParams(-1,dp(Math.max(50,b.h))));}s.addView(c);box.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button close=btn("Close");box.addView(close,new LinearLayout.LayoutParams(-1,dp(52)));Dialog d=new Dialog(this);d.setContentView(box);close.setOnClickListener(v->d.dismiss());d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(shape(SOFT,16));w.setLayout(-1,-1);}}
}
