package com.amb8657.websitebuilder;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.Drawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

public class BuilderV3Activity extends Activity {
    static final int PICK_IMAGE=73, MIN_W=60, MIN_H=40;
    final int BG=Color.rgb(12,15,22), PANEL=Color.rgb(24,29,39), WHITE=Color.WHITE, DIM=Color.rgb(164,171,186), ACCENT=Color.rgb(79,102,255);
    LinearLayout root,pages,tools; FrameLayout canvas; ScrollView canvasScroll; SharedPreferences sp;
    ArrayList<Project> projects=new ArrayList<>(); Project project; Page page; Block selected,imageTarget; int nextId=1;
    static class Project{String name;ArrayList<Page> pages=new ArrayList<>();Project(String n){name=n;}}
    static class Page{String name;int bg=Color.WHITE;ArrayList<Block> blocks=new ArrayList<>();Page(String n){name=n;}}
    static class Block{
        int id,parent=0,x=24,y=24,w=300,h=80,bg=Color.TRANSPARENT,bg2=Color.WHITE,tc=Color.DKGRAY,font=18;
        float opacity=1,radius=0; String type,text="",uri="",action="None",target="",fill="solid",animation="None"; boolean crop=false;
        Block(int i,String t,String s){id=i;type=t;text=s;}
    }
    interface ColorDone{void done(int c);}
    int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} float den(){return getResources().getDisplayMetrics().density;}
    GradientDrawable gd(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    Drawable fill(Block b){GradientDrawable g=new GradientDrawable();if("gradient".equals(b.fill))g.setColors(new int[]{b.bg,b.bg2});else g.setColor(b.bg);g.setCornerRadius(dp(b.radius));return g;}
    TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);b.setMinHeight(0);b.setMinWidth(0);b.setTextColor(Color.DKGRAY);b.setBackground(gd(WHITE,10));return b;}
    EditText edit(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(WHITE);e.setHintTextColor(DIM);e.setSingleLine();e.setBackground(gd(Color.rgb(23,22,27),8));e.setPadding(dp(10),0,dp(10),0);return e;}
    void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);}

    @Override public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("builder_v3",0);load();splash();}
    void splash(){base();root.setGravity(Gravity.CENTER);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(24),dp(24),dp(24),dp(24));TextView l=tv("G",52,WHITE);l.setGravity(Gravity.CENTER);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);l.setBackground(gd(ACCENT,28));c.addView(l,new LinearLayout.LayoutParams(dp(104),dp(104)));TextView t=tv("Website Builder",25,WHITE);t.setGravity(Gravity.CENTER);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(t,new LinearLayout.LayoutParams(-1,dp(62)));TextView x=tv("Create  •  Design  •  Publish",14,DIM);x.setGravity(Gravity.CENTER);c.addView(x,new LinearLayout.LayoutParams(-1,dp(36)));ProgressBar q=new ProgressBar(this);c.addView(q,new LinearLayout.LayoutParams(dp(30),dp(30)));root.addView(c,new LinearLayout.LayoutParams(-1,-2));new Handler().postDelayed(this::dashboard,1800);}

    void load(){projects.clear();String raw=sp.getString("data","");if(raw.isEmpty())return;try{JSONObject all=new JSONObject(raw);nextId=all.optInt("nextId",1);JSONArray ps=all.optJSONArray("projects");if(ps==null)return;for(int i=0;i<ps.length();i++){JSONObject po=ps.getJSONObject(i);Project p=new Project(po.optString("name","My Website"));JSONArray pa=po.optJSONArray("pages");if(pa!=null)for(int j=0;j<pa.length();j++){JSONObject qo=pa.getJSONObject(j);Page q=new Page(qo.optString("name","Home"));q.bg=qo.optInt("bg",Color.WHITE);JSONArray bs=qo.optJSONArray("blocks");if(bs!=null)for(int k=0;k<bs.length();k++){JSONObject o=bs.getJSONObject(k);Block x=new Block(o.optInt("id",nextId++),o.optString("type","Text"),o.optString("text",""));x.parent=o.optInt("parent",0);x.x=o.optInt("x",24);x.y=o.optInt("y",24);x.w=o.optInt("w",300);x.h=o.optInt("h",80);x.bg=o.optInt("bg",Color.TRANSPARENT);x.bg2=o.optInt("bg2",Color.WHITE);x.tc=o.optInt("tc",Color.DKGRAY);x.font=o.optInt("font",18);x.opacity=(float)o.optDouble("opacity",1);x.radius=(float)o.optDouble("radius",0);x.uri=o.optString("uri","");x.action=o.optString("action","None");x.target=o.optString("target","");x.fill=o.optString("fill","solid");x.crop=o.optBoolean("crop",false);x.animation=o.optString("animation","None");q.blocks.add(x);nextId=Math.max(nextId,x.id+1);}p.pages.add(q);}if(p.pages.isEmpty())p.pages.add(new Page("Home"));projects.add(p);}}catch(Exception ignored){}}
    void save(){try{JSONObject all=new JSONObject();all.put("nextId",nextId);JSONArray ps=new JSONArray();for(Project p:projects){JSONObject po=new JSONObject();po.put("name",p.name);JSONArray pa=new JSONArray();for(Page q:p.pages){JSONObject qo=new JSONObject();qo.put("name",q.name).put("bg",q.bg);JSONArray bs=new JSONArray();for(Block b:q.blocks){JSONObject o=new JSONObject();o.put("id",b.id).put("parent",b.parent).put("type",b.type).put("text",b.text).put("x",b.x).put("y",b.y).put("w",b.w).put("h",b.h).put("bg",b.bg).put("bg2",b.bg2).put("tc",b.tc).put("font",b.font).put("opacity",b.opacity).put("radius",b.radius).put("uri",b.uri).put("action",b.action).put("target",b.target).put("fill",b.fill).put("crop",b.crop).put("animation",b.animation);bs.put(o);}qo.put("blocks",bs);pa.put(qo);}po.put("pages",pa);ps.put(po);}all.put("projects",ps);sp.edit().putString("data",all.toString()).apply();}catch(Exception ignored){}}

    void dashboard(){base();LinearLayout h=new LinearLayout(this);h.setPadding(dp(18),dp(15),dp(18),dp(8));TextView l=tv("M",25,WHITE);l.setGravity(Gravity.CENTER);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);l.setBackground(gd(ACCENT,12));h.addView(l,new LinearLayout.LayoutParams(dp(46),dp(46)));TextView t=tv("  Website Builder",21,WHITE);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(t,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(h,new LinearLayout.LayoutParams(-1,dp(68)));root.addView(tv("My Websites",19,WHITE),new LinearLayout.LayoutParams(-1,dp(45)));ScrollView s=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(16),dp(8),dp(16),dp(24));s.addView(list);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button add=btn("+  New Website");add.setTextColor(WHITE);add.setBackground(gd(ACCENT,12));list.addView(add,new LinearLayout.LayoutParams(-1,dp(58)));add.setOnClickListener(v->newProject());for(Project p:projects){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(5),dp(5),dp(5));r.setBackground(gd(PANEL,12));TextView n=tv(p.name,16,WHITE);r.addView(n,new LinearLayout.LayoutParams(0,dp(60),1));Button m=btn("⋮");m.setTextColor(WHITE);r.addView(m,new LinearLayout.LayoutParams(dp(48),dp(44)));list.addView(r,new LinearLayout.LayoutParams(-1,dp(72)));r.setOnClickListener(v->openProject(p));m.setOnClickListener(v->projectMenu(p));}}
    void newProject(){EditText e=edit("Website name","My Website");new AlertDialog.Builder(this).setTitle("Name your website").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="My Website";project=new Project(n);project.pages.add(new Page("Home"));projects.add(0,project);page=project.pages.get(0);save();editor();}).show();}
    void openProject(Project p){project=p;page=p.pages.get(0);editor();}
    void projectMenu(Project p){new AlertDialog.Builder(this).setItems(new String[]{"Open","Rename","Delete"},(d,w)->{if(w==0)openProject(p);else if(w==1){EditText e=edit("Website name",p.name);new AlertDialog.Builder(this).setTitle("Rename").setView(e).setPositiveButton("Save",(x,y)->{p.name=e.getText().toString().trim();save();dashboard();}).setNegativeButton("Cancel",null).show();}else{projects.remove(p);save();dashboard();}}).show();}

    void editor(){base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹");top.addView(back,new LinearLayout.LayoutParams(dp(42),dp(46)));TextView title=tv(project.name,17,WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(title,new LinearLayout.LayoutParams(0,dp(46),1));Button preview=btn("Preview"),saveb=btn("Save"),pub=btn("Publish");preview.setTextColor(WHITE);saveb.setTextColor(WHITE);pub.setTextColor(WHITE);pub.setBackground(gd(ACCENT,8));top.addView(preview,new LinearLayout.LayoutParams(dp(78),dp(44)));top.addView(saveb,new LinearLayout.LayoutParams(dp(62),dp(44)));top.addView(pub,new LinearLayout.LayoutParams(dp(75),dp(44)));root.addView(top,new LinearLayout.LayoutParams(-1,dp(60)));back.setOnClickListener(v->{save();dashboard();});saveb.setOnClickListener(v->{save();Toast.makeText(this,"Saved",Toast.LENGTH_SHORT).show();});preview.setOnClickListener(v->preview());pub.setOnClickListener(v->preview());
        HorizontalScrollView ph=new HorizontalScrollView(this);pages=new LinearLayout(this);pages.setPadding(dp(8),dp(4),dp(8),dp(4));ph.addView(pages);root.addView(ph,new LinearLayout.LayoutParams(-1,dp(50)));HorizontalScrollView th=new HorizontalScrollView(this);tools=new LinearLayout(this);tools.setPadding(dp(8),dp(4),dp(8),dp(4));th.addView(tools);root.addView(th,new LinearLayout.LayoutParams(-1,dp(52)));canvasScroll=new ScrollView(this);canvas=new FrameLayout(this);canvasScroll.addView(canvas,new ScrollView.LayoutParams(-1,dp(760)));root.addView(canvasScroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bottom=new LinearLayout(this);bottom.setBackgroundColor(PANEL);Button pg=btn("Pages"),sty=btn("Style"),pv=btn("Preview");bottom.addView(pg,new LinearLayout.LayoutParams(0,dp(54),1));bottom.addView(sty,new LinearLayout.LayoutParams(0,dp(54),1));bottom.addView(pv,new LinearLayout.LayoutParams(0,dp(54),1));root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(64)));pg.setOnClickListener(v->pageManager());sty.setOnClickListener(v->pageStyle());pv.setOnClickListener(v->preview());render();}
    void render(){pages.removeAllViews();for(Page q:project.pages){Button b=btn(q.name);if(q==page)b.setBackground(gd(Color.rgb(55,43,92),8));b.setTextColor(q==page?WHITE:Color.DKGRAY);b.setOnClickListener(v->{page=q;selected=null;render();});pages.addView(b,new LinearLayout.LayoutParams(dp(105),dp(40)));}Button np=btn("＋ New");np.setOnClickListener(v->newPage());pages.addView(np,new LinearLayout.LayoutParams(dp(90),dp(40)));tools.removeAllViews();for(String s:new String[]{"Text","Image","Button","Section","Shape","Tool"}){Button b=btn("＋ "+s);b.setOnClickListener(v->add(s));tools.addView(b,new LinearLayout.LayoutParams(dp(92),dp(40)));}canvas.removeAllViews();canvas.setBackgroundColor(page.bg);int height=760;for(Block b:page.blocks)if(b.parent==0)height=Math.max(height,b.y+b.h+300);canvas.getLayoutParams().height=dp(height);canvas.requestLayout();for(Block b:page.blocks)if(b.parent==0)draw(canvas,b,0,0);}
    Block find(int id){for(Block b:page.blocks)if(b.id==id)return b;return null;}
    void draw(FrameLayout parent,Block b,int ox,int oy){FrameLayout h=new FrameLayout(this);h.setX(dp(b.x+ox));h.setY(dp(b.y+oy));h.setAlpha(b.opacity);h.setClipToOutline(true);h.setBackground(fill(b));View v;if("Image".equals(b.type)&&!b.uri.isEmpty()){ImageView im=new ImageView(this);im.setImageURI(Uri.parse(b.uri));im.setScaleType(b.crop?ImageView.ScaleType.CENTER_CROP:ImageView.ScaleType.FIT_CENTER);v=im;}else{TextView z=tv(b.text,b.font,b.tc);z.setGravity("Button".equals(b.type)||b.type.startsWith("Tool:")?Gravity.CENTER:Gravity.CENTER_VERTICAL);z.setPadding(dp(8),dp(4),dp(8),dp(4));if("Button".equals(b.type)||b.type.startsWith("Tool:"))z.setTextColor(WHITE);if("Section".equals(b.type)||"Shape".equals(b.type))z.setText("");v=z;}h.addView(v,new FrameLayout.LayoutParams(-1,-1));if(selected==b){h.setBackground(selectedFill(b));moveHandle(h,b);resizeHandle(h,b,Gravity.LEFT|Gravity.TOP);resizeHandle(h,b,Gravity.RIGHT|Gravity.TOP);resizeHandle(h,b,Gravity.LEFT|Gravity.BOTTOM);resizeHandle(h,b,Gravity.RIGHT|Gravity.BOTTOM);}h.setOnTouchListener((q,e)->move(h,e,b));parent.addView(h,new FrameLayout.LayoutParams(dp(Math.max(MIN_W,b.w)),dp(Math.max(MIN_H,b.h))));for(Block child:page.blocks)if(child.parent==b.id)draw(parent,child,b.x+ox,b.y+oy);}
    Drawable selectedFill(Block b){GradientDrawable g=(GradientDrawable)fill(b);g.setStroke(dp(2),ACCENT);return g;}
    void moveHandle(FrameLayout h,Block b){TextView m=tv("+",16,ACCENT);m.setGravity(Gravity.CENTER);m.setBackground(gd(WHITE,12));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(30),dp(30),Gravity.TOP|Gravity.CENTER_HORIZONTAL);lp.topMargin=-dp(34);h.addView(m,lp);m.setOnTouchListener((v,e)->move(h,e,b));}
    void resizeHandle(FrameLayout h,Block b,int g){TextView x=tv("",1,ACCENT);x.setBackground(gd(WHITE,8));h.addView(x,new FrameLayout.LayoutParams(dp(18),dp(18),g));x.setOnTouchListener((v,e)->resize(e,h,b,g));}
    boolean move(View v,MotionEvent e,Block b){if(e.getAction()==MotionEvent.ACTION_DOWN){v.getParent().requestDisallowInterceptTouchEvent(true);v.setTag(new float[]{e.getRawX(),e.getRawY(),b.x,b.y});selected=b;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float[] a=(float[])v.getTag();b.x=Math.max(0,(int)(a[2]+(e.getRawX()-a[0])/den()));b.y=Math.max(0,(int)(a[3]+(e.getRawY()-a[1])/den()));v.setX(dp(b.x));v.setY(dp(b.y));return true;}if(e.getAction()==MotionEvent.ACTION_UP){v.getParent().requestDisallowInterceptTouchEvent(false);save();render();showProperties(b);return true;}return true;}
    boolean resize(MotionEvent e,View v,Block b,int g){if(e.getAction()==MotionEvent.ACTION_DOWN){v.getParent().requestDisallowInterceptTouchEvent(true);v.setTag(new float[]{e.getRawX(),e.getRawY(),b.w,b.h,b.x,b.y,b.font});return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float[] a=(float[])v.getTag();float dx=(e.getRawX()-a[0])/den(),dy=(e.getRawY()-a[1])/den();int nw=Math.max(MIN_W,(int)a[2]+((g&Gravity.RIGHT)!=0?(int)dx:-(int)dx));int nh=Math.max(MIN_H,(int)a[3]+((g&Gravity.BOTTOM)!=0?(int)dy:-(int)dy));if((g&Gravity.LEFT)!=0)b.x=Math.max(0,(int)a[4]+(int)dx);if((g&Gravity.TOP)!=0)b.y=Math.max(0,(int)a[5]+(int)dy);b.w=nw;b.h=nh;if("Text".equals(b.type)||"Heading".equals(b.type)||"Button".equals(b.type)){float scale=Math.min(nw/(float)a[2],nh/(float)a[3]);b.font=Math.max(8,(int)(a[6]*Math.max(.5f,scale)));}v.setX(dp(b.x));v.setY(dp(b.y));ViewGroup.LayoutParams lp=v.getLayoutParams();lp.width=dp(nw);lp.height=dp(nh);v.setLayoutParams(lp);return true;}if(e.getAction()==MotionEvent.ACTION_UP){v.getParent().requestDisallowInterceptTouchEvent(false);save();render();return true;}return true;}

    void add(String type){if("Tool".equals(type)){toolPicker();return;}String s="Text".equals(type)?"Write your text here.":"Button".equals(type)?"Get Started":"";Block b=new Block(nextId++,type,s);b.y=40;for(Block q:page.blocks)if(q.parent==0)b.y=Math.max(b.y,q.y+q.h+24);b.w=300;b.h="Image".equals(type)?190:"Section".equals(type)?180:80;if("Section".equals(type)){b.bg=Color.rgb(245,245,248);b.radius=16;b.action="container";}if("Shape".equals(type)){b.bg=Color.rgb(220,220,230);b.radius=12;}if("Button".equals(type)){b.bg=ACCENT;b.tc=WHITE;b.radius=12;}if(selected!=null&&("Section".equals(selected.type)||("Shape".equals(selected.type)&&"container".equals(selected.action)))&&!("Section".equals(type))){b.parent=selected.id;b.x=20;b.y=20;}page.blocks.add(b);selected=b;save();render();if("Image".equals(type))pick(b);else showProperties(b);}
    void toolPicker(){String[] a={"Link","Email","Phone","Map"};new AlertDialog.Builder(this).setTitle("Add Tool").setItems(a,(d,w)->{Block b=new Block(nextId++,"Tool:"+a[w],a[w]);b.bg=ACCENT;b.tc=WHITE;b.radius=12;b.w=220;b.h=60;b.action=a[w];page.blocks.add(b);selected=b;save();render();toolTarget(b);}).show();}
    void toolTarget(Block b){String hint="Link".equals(b.action)?"https://":"";EditText e=edit("Target",hint);new AlertDialog.Builder(this).setTitle(b.action).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{b.target=e.getText().toString();save();showProperties(b);}).show();}

    void showProperties(Block b){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(10),dp(18),dp(10));box.setBackgroundColor(PANEL);box.addView(tv(b.type+" Properties",18,WHITE),new LinearLayout.LayoutParams(-1,dp(42)));EditText text=edit("Content",b.text);boolean textLike="Text".equals(b.type)||"Heading".equals(b.type)||"Button".equals(b.type)||b.type.startsWith("Tool:");box.addView(text,new LinearLayout.LayoutParams(-1,dp(50)));if(!textLike)text.setVisibility(View.GONE);EditText font=edit("Font size",String.valueOf(b.font));box.addView(font,new LinearLayout.LayoutParams(-1,dp(48)));if(!textLike)font.setVisibility(View.GONE);
        if(textLike){Button tc=btn("Text colour");box.addView(tc);Button an=btn("Animation: "+b.animation);box.addView(an);an.setOnClickListener(v->animationDialog(b,an));tc.setOnClickListener(v->picker(c->{b.tc=c;render();}));}
        if("Button".equals(b.type)||"Shape".equals(b.type)||"Section".equals(b.type)||b.type.startsWith("Tool:")){Button fill=btn("Fill / Gradient / Transparent");box.addView(fill);fill.setOnClickListener(v->fillDialog(b));Button rad=btn("Corner radius");box.addView(rad);rad.setOnClickListener(v->radius(b));}
        if("Image".equals(b.type)){Button rep=btn("Replace image");box.addView(rep);rep.setOnClickListener(v->pick(b));Button mode=btn(b.crop?"Image mode: Crop":"Image mode: Fit");box.addView(mode);mode.setOnClickListener(v->{b.crop=!b.crop;mode.setText(b.crop?"Image mode: Crop":"Image mode: Fit");render();});Button rad=btn("Corner radius");box.addView(rad);rad.setOnClickListener(v->radius(b));}
        if("Section".equals(b.type)||"Shape".equals(b.type)){Button cont=btn("Use as container: "+("container".equals(b.action)?"ON":"OFF"));box.addView(cont);cont.setOnClickListener(v->{b.action="container".equals(b.action)?"None":"container";cont.setText("Use as container: "+("container".equals(b.action)?"ON":"OFF"));save();});}
        if("Button".equals(b.type)){Button ac=btn("Action: "+b.action);box.addView(ac);ac.setOnClickListener(v->actions(b));}
        if(b.type.startsWith("Tool:")){Button tg=btn("Target: "+b.target);box.addView(tg);tg.setOnClickListener(v->toolTarget(b));}
        EditText w=edit("Width",String.valueOf(b.w)),h=edit("Height",String.valueOf(b.h));LinearLayout wh=new LinearLayout(this);wh.addView(w,new LinearLayout.LayoutParams(0,dp(48),1));wh.addView(h,new LinearLayout.LayoutParams(0,dp(48),1));box.addView(wh);SeekBar op=new SeekBar(this);op.setMax(100);op.setProgress((int)(b.opacity*100));box.addView(tv("Opacity",12,DIM));box.addView(op,new LinearLayout.LayoutParams(-1,dp(42)));op.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){b.opacity=p/100f;}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
        LinearLayout row=new LinearLayout(this);Button del=btn("Delete"),close=btn("Close"),apply=btn("Apply");row.addView(del,new LinearLayout.LayoutParams(0,dp(46),1));row.addView(close,new LinearLayout.LayoutParams(0,dp(46),1));apply.setTextColor(WHITE);apply.setBackground(gd(ACCENT,8));row.addView(apply,new LinearLayout.LayoutParams(0,dp(46),1));box.addView(row);Dialog d=new Dialog(this);d.setContentView(box);del.setOnClickListener(v->deleteBlock(b,d));close.setOnClickListener(v->d.dismiss());apply.setOnClickListener(v->{b.text=text.getText().toString();try{b.font=Math.max(8,Integer.parseInt(font.getText().toString()));}catch(Exception ignored){}try{b.w=Math.max(MIN_W,Integer.parseInt(w.getText().toString()));b.h=Math.max(MIN_H,Integer.parseInt(h.getText().toString()));}catch(Exception ignored){}save();d.dismiss();render();});d.show();Window q=d.getWindow();if(q!=null){q.setBackgroundDrawable(gd(PANEL,18));q.setGravity(Gravity.BOTTOM);q.setLayout(-1,WindowManager.LayoutParams.WRAP_CONTENT);}}
    void deleteBlock(Block b,Dialog d){boolean attached=!"None".equals(b.action)&&b.action.length()>0;new AlertDialog.Builder(this).setTitle("Delete "+b.type+"?").setMessage(attached?"This element has an attached action. Delete it and its attached action too?":"Delete this element?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(x,y)->{ArrayList<Block> rm=new ArrayList<>();rm.add(b);for(int i=0;i<rm.size();i++){Block z=rm.get(i);for(Block c:page.blocks)if(c.parent==z.id&&!rm.contains(c))rm.add(c);}page.blocks.removeAll(rm);selected=null;d.dismiss();save();render();}).show();}

    void fillDialog(Block b){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Solid","Gradient","Transparent"}));box.addView(s);Button c1=btn("Colour 1"),c2=btn("Colour 2");box.addView(c1);box.addView(c2);c2.setVisibility(View.GONE);s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){c2.setVisibility(pos==1?View.VISIBLE:View.GONE);}});c1.setOnClickListener(v->picker(c->{b.bg=c;c1.setText("Colour 1 selected");}));c2.setOnClickListener(v->picker(c->{b.bg2=c;c2.setText("Colour 2 selected");}));new AlertDialog.Builder(this).setTitle("Fill").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{int p=s.getSelectedItemPosition();b.fill=p==1?"gradient":p==2?"transparent":"solid";if(p==2)b.bg=Color.TRANSPARENT;save();render();}).show();}
    void picker(ColorDone done){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(8),dp(14),dp(8));Button black=btn("Black"),white=btn("White"),red=btn("Red"),blue=btn("Blue"),green=btn("Green"),yellow=btn("Yellow");for(Button b:new Button[]{black,white,red,blue,green,yellow})box.addView(b,new LinearLayout.LayoutParams(-1,dp(42)));black.setOnClickListener(v->doneColor(done,Color.BLACK));white.setOnClickListener(v->doneColor(done,Color.WHITE));red.setOnClickListener(v->doneColor(done,Color.RED));blue.setOnClickListener(v->doneColor(done,Color.BLUE));green.setOnClickListener(v->doneColor(done,Color.GREEN));yellow.setOnClickListener(v->doneColor(done,Color.YELLOW));EditText hex=edit("HEX #RRGGBB","#465CFF");box.addView(hex,new LinearLayout.LayoutParams(-1,dp(48)));new AlertDialog.Builder(this).setTitle("Choose a colour").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{try{String h=hex.getText().toString().trim();if(h.startsWith("#"))h=h.substring(1);long x=Long.parseLong(h,16);done.done(Color.rgb((int)(x>>16)&255,(int)(x>>8)&255,(int)x&255));}catch(Exception e){done.done(ACCENT);}}).show();}
    void doneColor(ColorDone d,int c){d.done(c);}




    void animationDialog(Block b,Button label){String[] a={"None","Fade In","Slide Up","Slide Left","Scale In"};new AlertDialog.Builder(this).setTitle("Animation / Interaction").setItems(a,(d,w)->{b.animation=a[w];label.setText("Animation: "+b.animation);save();}).show();}
    void applyAnimation(View v,Block b){if("Fade In".equals(b.animation)){v.setAlpha(0f);v.animate().alpha(b.opacity).setDuration(450).start();}else if("Slide Up".equals(b.animation)){v.setTranslationY(dp(30));v.animate().translationY(0).setDuration(450).start();}else if("Slide Left".equals(b.animation)){v.setTranslationX(dp(30));v.animate().translationX(0).setDuration(450).start();}else if("Scale In".equals(b.animation)){v.setScaleX(.75f);v.setScaleY(.75f);v.animate().scaleX(1).scaleY(1).setDuration(450).start();}}
    void radius(Block b){SeekBar s=new SeekBar(this);s.setMax(100);s.setProgress((int)b.radius);new AlertDialog.Builder(this).setTitle("Corner radius").setView(s).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{b.radius=s.getProgress();save();render();}).show();}
    void pick(Block b){imageTarget=b;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_IMAGE);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK_IMAGE&&c==RESULT_OK&&d!=null&&imageTarget!=null){imageTarget.uri=d.getData().toString();save();render();showProperties(imageTarget);}}

    void actions(Block b){String[] a={"Open Page","Open Website","Email","Phone"};new AlertDialog.Builder(this).setTitle("Button Action").setItems(a,(d,w)->{b.action=a[w];if(w==0)pageTarget(b);else{EditText e=edit("Target",w==1?"https://":"");new AlertDialog.Builder(this).setTitle(a[w]).setView(e).setPositiveButton("Apply",(x,y)->{b.target=e.getText().toString();save();}).setNegativeButton("Cancel",null).show();}}).show();}
    void pageTarget(Block b){ArrayList<String> a=new ArrayList<>();for(Page p:project.pages)a.add(p.name);new AlertDialog.Builder(this).setTitle("Open Page").setItems(a.toArray(new String[0]),(d,w)->{b.target=project.pages.get(w).name;save();}).show();}
    void newPage(){EditText e=edit("Page name","");new AlertDialog.Builder(this).setTitle("Create New Page").setView(e).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="New Page";page=new Page(n);project.pages.add(page);selected=null;save();render();}).setNegativeButton("Cancel",null).show();}
    void pageManager(){ArrayList<String> a=new ArrayList<>();for(Page p:project.pages)a.add(p.name);a.add("＋ New Page");new AlertDialog.Builder(this).setTitle("Pages").setItems(a.toArray(new String[0]),(d,w)->{if(w==project.pages.size())newPage();else{page=project.pages.get(w);selected=null;render();}}).show();}
    void pageStyle(){new AlertDialog.Builder(this).setTitle("Page background").setItems(new String[]{"White","Soft Gray","Black","Purple Tint"},(d,w)->{page.bg=new int[]{Color.WHITE,Color.rgb(245,245,248),Color.rgb(20,20,24),Color.rgb(247,244,255)}[w];save();render();}).show();}

    void preview(){final Dialog d=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);TextView bar=tv("Preview • "+page.name,18,WHITE);bar.setPadding(dp(16),0,0,0);bar.setBackgroundColor(BG);box.addView(bar,new LinearLayout.LayoutParams(-1,dp(54)));ScrollView s=new ScrollView(this);FrameLayout c=new FrameLayout(this);c.setBackgroundColor(page.bg);s.addView(c,new ScrollView.LayoutParams(-1,dp(760)));box.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button close=btn("Close");box.addView(close,new LinearLayout.LayoutParams(-1,dp(52)));close.setOnClickListener(v->d.dismiss());d.setContentView(box);for(Block b:page.blocks)if(b.parent==0)previewBlock(c,b,0,0,d);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(gd(WHITE,16));w.setLayout(-1,-1);}}
    void previewBlock(FrameLayout p,Block b,int ox,int oy,Dialog d){View v;if("Image".equals(b.type)&&!b.uri.isEmpty()){ImageView im=new ImageView(this);im.setImageURI(Uri.parse(b.uri));im.setScaleType(b.crop?ImageView.ScaleType.CENTER_CROP:ImageView.ScaleType.FIT_CENTER);v=im;}else{TextView t=tv(b.text,b.font,b.tc);t.setGravity(("Button".equals(b.type)||b.type.startsWith("Tool:"))?Gravity.CENTER:Gravity.CENTER_VERTICAL);t.setPadding(dp(8),dp(4),dp(8),dp(4));if("Button".equals(b.type)||b.type.startsWith("Tool:"))t.setTextColor(WHITE);if("Section".equals(b.type)||"Shape".equals(b.type))t.setText("");v=t;}v.setBackground(fill(b));v.setAlpha(b.opacity);applyAnimation(v,b);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(Math.max(MIN_W,b.w)),dp(Math.max(MIN_H,b.h)));lp.leftMargin=dp(b.x+ox);lp.topMargin=dp(b.y+oy);p.addView(v,lp);if("Button".equals(b.type)||b.type.startsWith("Tool:"))v.setOnClickListener(x->runAction(b,d));for(Block c:page.blocks)if(c.parent==b.id)previewBlock(p,c,b.x+ox,b.y+oy,d);}
    void runAction(Block b,Dialog d){try{if("Open Page".equals(b.action)){for(Page p:project.pages)if(p.name.equals(b.target)){page=p;d.dismiss();preview();return;}}else if("Open Website".equals(b.action))startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(b.target)));else if("Email".equals(b.action))startActivity(new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:"+b.target)));else if("Phone".equals(b.action))startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+b.target)));else if("Link".equals(b.action))startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(b.target)));else if("Map".equals(b.action))startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q="+Uri.encode(b.target))));}catch(Exception ignored){}}
}
