package com.amb8657.websitebuilder;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.view.*;
import android.webkit.WebView;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class MainActivity extends Activity {
 static final int PICK_IMAGE=41, EXPORT_ZIP=9001;
 final int BG=Color.rgb(19,18,23), CHROME=Color.rgb(23,22,27), SOFT=Color.rgb(31,30,36), TEXT=Color.rgb(237,235,243), DIM=Color.rgb(156,153,168), ACCENT=Color.rgb(124,92,255);
 LinearLayout root,pagesRow,toolsRow,canvas,bottom; EditText projectName; SharedPreferences prefs;
 ArrayList<Page> pages=new ArrayList<>(); int current=0; Block selected;
 static class Block {String type,text,uri;Block(String t,String x){type=t;text=x;uri="";}Block(String t,String x,String u){type=t;text=x;uri=u;}}
 static class Page {String name;ArrayList<Block> blocks=new ArrayList<>();Page(String n){name=n;}}
 int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
 LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w<0?w:dp(w),h<0?h:dp(h));}
 LinearLayout.LayoutParams weight(float w,int h){return new LinearLayout.LayoutParams(0,h<0?h:dp(h),w);}
 GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setAllCaps(false);b.setTextColor(TEXT);b.setPadding(dp(10),0,dp(10),0);b.setMinHeight(0);b.setMinWidth(0);b.setBackground(shape(SOFT,8));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(CHROME);getWindow().setNavigationBarColor(SOFT);prefs=getSharedPreferences("wb",0);load();build();render();}
 void build(){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setBackgroundColor(CHROME);root.addView(top,lp(-1,104));
  LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);titleRow.setPadding(dp(10),dp(5),dp(10),dp(3));top.addView(titleRow,lp(-1,52));
  TextView mark=tv("P",14,Color.WHITE);mark.setGravity(Gravity.CENTER);mark.setTypeface(Typeface.DEFAULT_BOLD);mark.setBackground(shape(ACCENT,7));titleRow.addView(mark,lp(28,28));
  TextView brand=tv("Website Builder",14,TEXT);brand.setTypeface(Typeface.DEFAULT_BOLD);brand.setPadding(dp(8),0,dp(6),0);titleRow.addView(brand,lp(116,44));
  projectName=new EditText(this);projectName.setText(prefs.getString("project","My Website"));projectName.setTextColor(TEXT);projectName.setTextSize(13);projectName.setSingleLine();projectName.setEllipsize(android.text.TextUtils.TruncateAt.END);projectName.setBackgroundColor(Color.TRANSPARENT);titleRow.addView(projectName,weight(1,42));
  LinearLayout actionRow=new LinearLayout(this);actionRow.setGravity(Gravity.CENTER_VERTICAL);actionRow.setPadding(dp(10),dp(2),dp(10),dp(6));top.addView(actionRow,lp(-1,52));
  Button importB=btn("Import"),code=btn("Code"),download=btn("Export");actionRow.addView(importB,weight(1,40));actionRow.addView(code,weight(1,40));download.setTextColor(Color.WHITE);download.setBackground(shape(ACCENT,8));actionRow.addView(download,weight(1,40));
  LinearLayout work=new LinearLayout(this);work.setOrientation(LinearLayout.VERTICAL);root.addView(work,new LinearLayout.LayoutParams(-1,0,1));
  HorizontalScrollView psv=new HorizontalScrollView(this);psv.setHorizontalScrollBarEnabled(false);pagesRow=new LinearLayout(this);pagesRow.setGravity(Gravity.CENTER_VERTICAL);pagesRow.setPadding(dp(8),dp(5),dp(8),dp(5));psv.addView(pagesRow);work.addView(psv,lp(-1,52));
  HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);toolsRow=new LinearLayout(this);toolsRow.setPadding(dp(8),dp(6),dp(8),dp(6));toolsRow.setGravity(Gravity.CENTER_VERTICAL);hsv.addView(toolsRow);work.addView(hsv,lp(-1,50));
  ScrollView sv=new ScrollView(this);sv.setFillViewport(true);canvas=new LinearLayout(this);canvas.setOrientation(LinearLayout.VERTICAL);canvas.setPadding(dp(10),dp(16),dp(10),dp(90));canvas.setBackgroundColor(BG);sv.addView(canvas);work.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  bottom=new LinearLayout(this);bottom.setGravity(Gravity.CENTER_VERTICAL);bottom.setPadding(dp(8),dp(5),dp(8),dp(5));bottom.setBackgroundColor(SOFT);root.addView(bottom,lp(-1,64));
  Button pagesBtn=btn("Pages"),theme=btn("Theme"),preview=btn("Preview"),save=btn("Save");bottom.addView(pagesBtn,weight(1,52));bottom.addView(theme,weight(1,52));bottom.addView(preview,weight(1,52));bottom.addView(save,weight(1,52));
  projectName.setOnFocusChangeListener((v,f)->{if(!f){save();renderPages();}});save.setOnClickListener(v->saveVersionDialog());pagesBtn.setOnClickListener(v->pageManager());theme.setOnClickListener(v->themeDialog());preview.setOnClickListener(v->previewTest());importB.setOnClickListener(v->importDialog());code.setOnClickListener(v->showCode());download.setOnClickListener(v->chooseExport());
  String[] ts={"Heading","Text","Image","Button","Divider","Spacer"};for(String s:ts){Button x=btn("+ "+s);x.setOnClickListener(v->addBlock(s));toolsRow.addView(x,lp(92,38));}
 }
 void renderPages(){pagesRow.removeAllViews();for(int i=0;i<pages.size();i++){final int n=i;Button b=btn(pages.get(i).name);if(i==current)b.setBackground(shape(Color.rgb(36,28,58),8));b.setOnClickListener(v->{current=n;selected=null;render();});pagesRow.addView(b,lp(100,40));}Button add=btn("+ New");add.setOnClickListener(v->addPage());pagesRow.addView(add,lp(75,40));}
 void render(){renderPages();canvas.removeAllViews();for(int i=0;i<pages.get(current).blocks.size();i++)canvas.addView(blockView(pages.get(current).blocks.get(i),i));if(pages.get(current).blocks.isEmpty()){TextView e=tv("This page is empty.\n\nAdd a block from the toolbar above to get started.",14,DIM);e.setGravity(Gravity.CENTER);e.setBackground(shape(Color.WHITE,9));canvas.addView(e,lp(-1,250));}}
 TextView blockView(Block b,int index){TextView v=tv(b.text,16,Color.rgb(40,39,45));v.setPadding(dp(12),dp(10),dp(12),dp(10));v.setBackground(shape(Color.WHITE,8));int h=82;if(b.type.equals("Heading")){v.setTextSize(28);v.setTypeface(Typeface.DEFAULT_BOLD);h=100;}else if(b.type.equals("Image")){h=175;v.setGravity(Gravity.CENTER);v.setText(b.uri.isEmpty()?"Image\nTap to choose image":fileName(Uri.parse(b.uri)));}else if(b.type.equals("Button")){v.setGravity(Gravity.CENTER);v.setTextColor(Color.WHITE);v.setBackground(shape(ACCENT,8));}else if(b.type.equals("Divider")){h=22;v.setText("");v.setBackgroundColor(Color.rgb(225,223,230));}else if(b.type.equals("Spacer")){h=45;v.setText("");v.setBackgroundColor(Color.TRANSPARENT);}LinearLayout.LayoutParams p=lp(-1,h);p.setMargins(0,0,0,dp(6));v.setLayoutParams(p);v.setOnClickListener(x->{selected=b;editBlock(b);});return v;}
 void addBlock(String type){String x="";if(type.equals("Heading"))x="Your Heading Here";if(type.equals("Text"))x="Write something here. Select this block to edit it.";if(type.equals("Image"))x="Image";if(type.equals("Button"))x="Click Me";Block b=new Block(type,x);pages.get(current).blocks.add(b);selected=b;save();render();if(type.equals("Image"))pickImage();else editBlock(b);}
 void editBlock(Block b){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(10),dp(18),dp(8));box.setBackgroundColor(SOFT);TextView title=tv(b.type+" block",14,TEXT);title.setTypeface(Typeface.DEFAULT_BOLD);box.addView(title,lp(-1,42));EditText e=new EditText(this);e.setText(b.text);e.setTextColor(TEXT);e.setTextSize(14);e.setGravity(Gravity.TOP);e.setBackground(shape(CHROME,8));e.setPadding(dp(10),dp(9),dp(10),dp(9));box.addView(e,lp(-1,90));LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(10),0,0);Button cancel=btn("Close"),del=btn("Delete"),apply=btn("Apply");row.addView(cancel,weight(1,42));row.addView(del,weight(1,42));apply.setBackground(shape(ACCENT,8));row.addView(apply,weight(1,42));box.addView(row);final Dialog d=new Dialog(this);d.setContentView(box);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(shape(SOFT,18));w.setGravity(Gravity.BOTTOM);}cancel.setOnClickListener(v->d.dismiss());del.setOnClickListener(v->{pages.get(current).blocks.remove(b);selected=null;save();render();d.dismiss();});apply.setOnClickListener(v->{b.text=e.getText().toString();save();render();d.dismiss();});d.show();if(w!=null)w.setLayout(-1,WindowManager.LayoutParams.WRAP_CONTENT);}
 void addPage(){final EditText e=new EditText(this);e.setHint("Page name");new AlertDialog.Builder(this).setTitle("New page").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="New Page";pages.add(0,new Page(n));current=0;save();render();}).show();}
 void pageManager(){String[] names=new String[pages.size()+1];for(int i=0;i<pages.size();i++)names[i]=pages.get(i).name;names[pages.size()]= "+ New page";new AlertDialog.Builder(this).setTitle("Pages").setItems(names,(d,w)->{if(w<pages.size()){current=w;render();}else addPage();}).show();}
 void themeDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(12),dp(20),0);box.addView(tv("Background color",12,DIM));EditText e=new EditText(this);e.setText("#FFFFFF");e.setTextColor(TEXT);e.setBackground(shape(CHROME,8));box.addView(e,lp(-1,50));new AlertDialog.Builder(this).setTitle("Page settings").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply",null).show();}
 void previewTest(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),0,dp(8),dp(4));TextView status=tv("TEST MODE • Draft only • Live site is unchanged",12,DIM);status.setPadding(dp(8),dp(4),dp(8),dp(8));box.addView(status,lp(-1,38));WebView w=new WebView(this);w.getSettings().setJavaScriptEnabled(true);w.loadDataWithBaseURL(null,fullSiteHtml(),"text/html","UTF-8",null);box.addView(w,new LinearLayout.LayoutParams(-1,0,1));LinearLayout actions=new LinearLayout(this);actions.setPadding(0,dp(6),0,0);Button browser=btn("Open in Browser"),history=btn("Versions"),close=btn("Close");actions.addView(browser,weight(1,44));actions.addView(history,weight(1,44));actions.addView(close,weight(1,44));box.addView(actions);Dialog d=new Dialog(this);d.setContentView(box);browser.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("data:text/html;charset=utf-8,"+Uri.encode(fullSiteHtml())));try{startActivity(i);}catch(Exception e){Toast.makeText(this,"No browser available",Toast.LENGTH_SHORT).show();}});history.setOnClickListener(v->versionHistory());close.setOnClickListener(v->d.dismiss());d.show();Window win=d.getWindow();if(win!=null){win.setBackgroundDrawable(shape(SOFT,16));win.setLayout(-1,-1);}}
 void saveVersionDialog(){final EditText name=new EditText(this);name.setHint("Version name, e.g. Home redesign");name.setSingleLine();AlertDialog d=new AlertDialog.Builder(this).setTitle("Save draft version").setMessage("Save the current draft as a named version. This does not change the live site.").setView(name).setNegativeButton("Cancel",null).setPositiveButton("Save Version",null).create();d.setOnShowListener(x->{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String n=name.getText().toString().trim();if(n.isEmpty())n="Version "+(prefs.getInt("versionCount",0)+1);saveVersion(n);Toast.makeText(this,"Saved: "+n,Toast.LENGTH_SHORT).show();d.dismiss();});});d.show();}
 void saveVersion(String name){int count=prefs.getInt("versionCount",0);SharedPreferences.Editor e=prefs.edit();e.putString("v"+count+"name",name).putLong("v"+count+"time",System.currentTimeMillis()).putInt("v"+count+"count",pages.size());for(int i=0;i<pages.size();i++){Page p=pages.get(i);e.putString("v"+count+"p"+i+"name",p.name).putInt("v"+count+"p"+i+"bc",p.blocks.size());for(int j=0;j<p.blocks.size();j++){Block b=p.blocks.get(j);e.putString("v"+count+"p"+i+"b"+j+"t",b.type).putString("v"+count+"p"+i+"b"+j+"x",b.text).putString("v"+count+"p"+i+"b"+j+"u",b.uri);}}e.putInt("versionCount",count+1).apply();}
 void versionHistory(){int count=prefs.getInt("versionCount",0);if(count==0){Toast.makeText(this,"No saved versions yet",Toast.LENGTH_SHORT).show();return;}String[] names=new String[count];for(int i=0;i<count;i++)names[i]=prefs.getString("v"+i+"name","Version "+(i+1));new AlertDialog.Builder(this).setTitle("Version history").setItems(names,(d,w)->restoreVersion(w)).show();}
 void restoreVersion(int slot){int count=prefs.getInt("v"+slot+"count",0);ArrayList<Page> restored=new ArrayList<>();for(int i=0;i<count;i++){Page p=new Page(prefs.getString("v"+slot+"p"+i+"name","Page "+i));int bc=prefs.getInt("v"+slot+"p"+i+"bc",0);for(int j=0;j<bc;j++)p.blocks.add(new Block(prefs.getString("v"+slot+"p"+i+"b"+j+"t","Text"),prefs.getString("v"+slot+"p"+i+"b"+j+"x",""),prefs.getString("v"+slot+"p"+i+"b"+j+"u","")));restored.add(p);}if(!restored.isEmpty()){pages=restored;current=0;save();render();Toast.makeText(this,"Restored "+prefs.getString("v"+slot+"name","version"),Toast.LENGTH_SHORT).show();}}
 void importDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText name=new EditText(this);name.setHint("Page name");EditText code=new EditText(this);code.setHint("Paste HTML");code.setGravity(Gravity.TOP);box.addView(name);box.addView(code,lp(-1,180));new AlertDialog.Builder(this).setTitle("Import HTML").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Import",(d,w)->{Page p=new Page(name.getText().toString().trim().isEmpty()?"Imported Page":name.getText().toString());p.blocks.add(new Block("Text",code.getText().toString()));pages.add(0,p);current=0;save();render();}).show();}
 void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_IMAGE);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PICK_IMAGE){Uri u=d.getData();if(selected!=null){selected.type="Image";selected.text="Image";selected.uri=u.toString();}else pages.get(current).blocks.add(new Block("Image","Image",u.toString()));save();render();}else if(r==EXPORT_ZIP){exportZip(d.getData());}}
 String fileName(Uri u){Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){try{int n=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&n>=0)return c.getString(n);}finally{c.close();}}return "image";}
 void chooseExport(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"website-builder-site.zip");startActivityForResult(i,EXPORT_ZIP);}
 void exportZip(Uri uri){try{OutputStream raw=getContentResolver().openOutputStream(uri);ZipOutputStream z=new ZipOutputStream(raw);for(Page p:pages){String file=pageFileName(p);z.putNextEntry(new ZipEntry(file));z.write(pageHtml(p).getBytes("UTF-8"));z.closeEntry();}z.putNextEntry(new ZipEntry("README.txt"));z.write(("Website Builder export\nProject: "+projectName.getText().toString()+"\nPages: "+pages.size()+"\n\nindex.html is the Home page. Other pages are exported as separate HTML files.\n").getBytes("UTF-8"));z.closeEntry();z.close();raw.close();Toast.makeText(this,"Website ZIP exported",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 String pageFileName(Page p){String n=p.name.toLowerCase(Locale.US).replaceAll("[^a-z0-9]+","-");if(n.isEmpty())n="page";if(n.equals("home"))return "index.html";return n+".html";}
 void save(){SharedPreferences.Editor e=prefs.edit();e.putInt("count",pages.size()).putInt("current",current).putString("project",projectName==null?"My Website":projectName.getText().toString());for(int i=0;i<pages.size();i++){Page p=pages.get(i);e.putString("p"+i+"name",p.name).putInt("p"+i+"bc",p.blocks.size());for(int j=0;j<p.blocks.size();j++){Block b=p.blocks.get(j);e.putString("p"+i+"b"+j+"t",b.type).putString("p"+i+"b"+j+"x",b.text).putString("p"+i+"b"+j+"u",b.uri);}}e.apply();}
 void load(){int n=prefs.getInt("count",0);if(n==0){pages.add(new Page("Home"));return;}for(int i=0;i<n;i++){Page p=new Page(prefs.getString("p"+i+"name","Page "+i));int c=prefs.getInt("p"+i+"bc",0);for(int j=0;j<c;j++)p.blocks.add(new Block(prefs.getString("p"+i+"b"+j+"t","Text"),prefs.getString("p"+i+"b"+j+"x",""),prefs.getString("p"+i+"b"+j+"u","")));pages.add(p);}current=Math.min(prefs.getInt("current",0),pages.size()-1);}
 String fullSiteHtml(){StringBuilder h=new StringBuilder("<!doctype html><html><head><meta name=viewport content=\"width=device-width,initial-scale=1\"><style>body{margin:0;font-family:Arial;color:#17161b}.site{max-width:860px;margin:auto;padding:35px 22px}.nav{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:30px}.nav a{color:#7c5cff}.hero{font-size:34px;font-weight:700;margin-bottom:16px}.para{line-height:1.6}.btn{display:inline-block;background:#7c5cff;color:#fff;padding:11px 22px;border-radius:8px;text-decoration:none}.divider{height:1px;background:#ddd;margin:24px 0}.spacer{height:40px}</style></head><body><main class=site><nav class=nav>");for(Page p:pages)h.append("<a href=\"").append(pageFileName(p)).append("\">").append(esc(p.name)).append("</a>");h.append("</nav>");for(Block b:pages.get(current).blocks)appendBlock(h,b);return h.append("</main></body></html>").toString();}
 String pageHtml(Page page){StringBuilder h=new StringBuilder("<!doctype html><html><head><meta name=viewport content=\"width=device-width,initial-scale=1\"><style>body{margin:0;font-family:Arial;color:#17161b}.site{max-width:860px;margin:auto;padding:35px 22px}.nav{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:30px}.nav a{color:#7c5cff}.hero{font-size:34px;font-weight:700;margin-bottom:16px}.para{line-height:1.6}.btn{display:inline-block;background:#7c5cff;color:#fff;padding:11px 22px;border-radius:8px;text-decoration:none}.divider{height:1px;background:#ddd;margin:24px 0}.spacer{height:40px}</style></head><body><main class=site><nav class=nav>");for(Page p:pages)h.append("<a href=\"").append(pageFileName(p)).append("\">").append(esc(p.name)).append("</a>");h.append("</nav>");for(Block b:page.blocks)appendBlock(h,b);return h.append("</main></body></html>").toString();}
 void appendBlock(StringBuilder h,Block b){if(b.type.equals("Heading"))h.append("<div class=hero>").append(esc(b.text)).append("</div>");else if(b.type.equals("Text"))h.append("<p class=para>").append(esc(b.text)).append("</p>");else if(b.type.equals("Button"))h.append("<a class=btn href=\"#\">").append(esc(b.text)).append("</a>");else if(b.type.equals("Image")&&!b.uri.isEmpty())h.append("<p>Image: ").append(esc(fileName(Uri.parse(b.uri)))).append("</p>");else if(b.type.equals("Divider"))h.append("<div class=divider></div>");else if(b.type.equals("Spacer"))h.append("<div class=spacer></div>");}
 String html(){return pageHtml(pages.get(current));}
 String esc(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
}
