package com.amb8657.websitebuilder;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.util.Base64;
import android.view.*;
import android.webkit.WebView;
import android.widget.*;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity {
 static final int PICK_IMAGE=41, CREATE_HTML=42;
 LinearLayout root,canvas,toolbar; TextView projectTitle,pageTitle,status;
 ArrayList<Page> pages=new ArrayList<>(); int currentPage=0; SharedPreferences prefs;
 static class Block {String type,text,imageUri; Block(String t,String x){type=t;text=x;imageUri="";} Block(String t,String x,String u){type=t;text=x;imageUri=u;}}
 static class Page {String name; ArrayList<Block> blocks=new ArrayList<>(); Page(String n){name=n;}}
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("website_builder",MODE_PRIVATE);load();build();render();}
 TextView label(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(28,30,34));v.setPadding(16,10,16,10);return v;}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 Button action(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setAllCaps(false);b.setBackground(bg(Color.WHITE,18));return b;}
 Page page(){return pages.get(currentPage);}
 void build(){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,247,249));
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(8,6,8,6);top.setBackgroundColor(Color.WHITE);
  TextView app=label("Website Builder",18);app.setTypeface(Typeface.DEFAULT_BOLD);top.addView(app,new LinearLayout.LayoutParams(145,56));
  projectTitle=label("My Website",17);projectTitle.setTypeface(Typeface.DEFAULT_BOLD);top.addView(projectTitle,new LinearLayout.LayoutParams(0,56,1));
  Button save=action("Save"),preview=action("Preview"),export=action("Export");top.addView(save,new LinearLayout.LayoutParams(74,52));top.addView(preview,new LinearLayout.LayoutParams(86,52));top.addView(export,new LinearLayout.LayoutParams(78,52));root.addView(top);
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(8,4,8,4);bar.setBackgroundColor(Color.WHITE);Button pb=action("Pages");pageTitle=label("Home",14);bar.addView(pb,new LinearLayout.LayoutParams(75,44));bar.addView(pageTitle,new LinearLayout.LayoutParams(0,44,1));Button rename=action("Rename");bar.addView(rename,new LinearLayout.LayoutParams(82,44));status=label("Saved locally",11);bar.addView(status,new LinearLayout.LayoutParams(125,44));root.addView(bar);
  HorizontalScrollView hs=new HorizontalScrollView(this);toolbar=new LinearLayout(this);toolbar.setPadding(8,6,8,6);String[] ts={"Heading","Text","Button","Image","Section","Card","Navbar","Divider","Spacer","Footer"};for(String t:ts){Button x=action("+ "+t);x.setOnClickListener(v->addBlock(t));toolbar.addView(x,new LinearLayout.LayoutParams(108,48));}hs.addView(toolbar);root.addView(hs,new LinearLayout.LayoutParams(-1,62));
  ScrollView sv=new ScrollView(this);canvas=new LinearLayout(this);canvas.setOrientation(LinearLayout.VERTICAL);canvas.setPadding(18,18,18,90);canvas.setBackgroundColor(Color.rgb(232,234,238));sv.addView(canvas);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout bottom=new LinearLayout(this);bottom.setPadding(8,5,8,5);bottom.setBackgroundColor(Color.WHITE);Button pagesBtn=action("Pages"),assets=action("Assets"),clear=action("Clear"),settings=action("Settings");bottom.addView(pagesBtn,new LinearLayout.LayoutParams(0,54,1));bottom.addView(assets,new LinearLayout.LayoutParams(0,54,1));bottom.addView(clear,new LinearLayout.LayoutParams(0,54,1));bottom.addView(settings,new LinearLayout.LayoutParams(0,54,1));root.addView(bottom);setContentView(root);
  save.setOnClickListener(v->save());preview.setOnClickListener(v->preview());export.setOnClickListener(v->chooseExport());pb.setOnClickListener(v->pageManager());pagesBtn.setOnClickListener(v->pageManager());rename.setOnClickListener(v->renameProject());assets.setOnClickListener(v->pickImage());clear.setOnClickListener(v->{page().blocks.clear();render();save();});settings.setOnClickListener(v->settings());
 }
 void addBlock(String t){String x="";if(t.equals("Heading"))x="Your headline";else if(t.equals("Text"))x="Tell visitors about your work, services or project.";else if(t.equals("Button"))x="Get Started";else if(t.equals("Image"))x="Choose an image";else if(t.equals("Section"))x="New Section";else if(t.equals("Card"))x="Card title\nShort description";else if(t.equals("Navbar"))x="Home   About   Projects   Contact";else if(t.equals("Footer"))x="© 2026 Your Website";page().blocks.add(new Block(t,x));render();save();}
 TextView blockView(int i){Block b=page().blocks.get(i);TextView v=label(b.text,b.type.equals("Heading")?27:16);v.setGravity(Gravity.CENTER_VERTICAL);v.setBackground(bg(Color.WHITE,16));if(b.type.equals("Heading")){v.setTypeface(Typeface.DEFAULT_BOLD);v.setGravity(Gravity.CENTER);v.getLayoutParams();}if(b.type.equals("Button")){v.setGravity(Gravity.CENTER);v.setTextColor(Color.WHITE);v.setBackground(bg(Color.rgb(38,40,45),16));}if(b.type.equals("Footer")){v.setGravity(Gravity.CENTER);v.setTextColor(Color.WHITE);v.setBackground(bg(Color.rgb(34,35,39),16));}if(b.type.equals("Image")){v.setGravity(Gravity.CENTER);v.setBackground(bg(Color.rgb(218,221,226),16));if(!b.imageUri.isEmpty())v.setText("IMAGE\n"+fileName(Uri.parse(b.imageUri)));}int h=b.type.equals("Heading")?108:b.type.equals("Image")?190:b.type.equals("Footer")?70:b.type.equals("Spacer")?42:b.type.equals("Divider")?24:b.type.equals("Navbar")?60:82;LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,h);p.setMargins(0,0,0,10);v.setLayoutParams(p);v.setOnClickListener(x->editBlock(i));return v;}
 void render(){canvas.removeAllViews();pageTitle.setText(page().name);for(int i=0;i<page().blocks.size();i++)canvas.addView(blockView(i));if(page().blocks.isEmpty()){TextView e=label("Start building\n\nTap an element above to add it to this page.",18);e.setGravity(Gravity.CENTER);e.setTextColor(Color.GRAY);canvas.addView(e,new LinearLayout.LayoutParams(-1,280));}}
 void editBlock(int i){Block b=page().blocks.get(i);EditText e=new EditText(this);e.setText(b.text);new AlertDialog.Builder(this).setTitle("Edit "+b.type).setView(e).setNeutralButton("Delete",(d,w)->{page().blocks.remove(i);render();save();}).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{b.text=e.getText().toString();render();save();}).show();}
 void renameProject(){EditText e=new EditText(this);e.setText(projectTitle.getText());new AlertDialog.Builder(this).setTitle("Project name").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{projectTitle.setText(e.getText().toString());save();}).show();}
 void pageManager(){String[] n=new String[pages.size()+2];for(int i=0;i<pages.size();i++)n[i]=pages.get(i).name;n[pages.size()]= "+ Add page";n[pages.size()+1]="Rename current page";new AlertDialog.Builder(this).setTitle("Pages").setItems(n,(d,w)->{if(w<pages.size()){currentPage=w;render();}else if(w==pages.size())addPage();else renamePage();}).show();}
 void addPage(){EditText e=new EditText(this);e.setHint("Page name");new AlertDialog.Builder(this).setTitle("New page").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="Page "+(pages.size()+1);pages.add(new Page(n));currentPage=pages.size()-1;render();save();}).show();}
 void renamePage(){EditText e=new EditText(this);e.setText(page().name);new AlertDialog.Builder(this).setTitle("Rename page").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{page().name=e.getText().toString();render();save();}).show();}
 void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_IMAGE);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PICK_IMAGE){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}page().blocks.add(new Block("Image","Image",u.toString()));render();save();}else if(r==CREATE_HTML)writeHtml(d.getData());}
 String fileName(Uri u){Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){try{int n=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&n>=0)return c.getString(n);}finally{c.close();}}return "image";}
 void chooseExport(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/html");i.putExtra(Intent.EXTRA_TITLE,"website.html");startActivityForResult(i,CREATE_HTML);}
 void writeHtml(Uri u){try{OutputStream o=getContentResolver().openOutputStream(u);o.write(html().getBytes("UTF-8"));o.close();Toast.makeText(this,"Website exported successfully",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export failed",Toast.LENGTH_LONG).show();}}
 String esc(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 String imageData(String s){try{Uri u=Uri.parse(s);InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)o.write(b,0,n);in.close();String m=getContentResolver().getType(u);return "data:"+(m==null?"image/jpeg":m)+";base64,"+Base64.encodeToString(o.toByteArray(),Base64.NO_WRAP);}catch(Exception e){return "";}}
 String html(){StringBuilder h=new StringBuilder("<!doctype html><html><head><meta name=viewport content=\"width=device-width,initial-scale=1\"><title>Website</title><style>body{font-family:Arial;margin:0;color:#1c1e22}.site{max-width:1100px;margin:auto;padding:20px}.hero{text-align:center;padding:60px}.section,.card{padding:30px;margin:12px 0;background:#f4f5f7;border-radius:16px}.btn{display:inline-block;background:#26282d;color:white;padding:13px 22px;border-radius:10px;text-decoration:none}.nav{padding:18px;border-bottom:1px solid #ddd}.footer{padding:30px;text-align:center;background:#222;color:white}.image{max-width:100%;border-radius:14px}</style></head><body><div class=site>");for(Block b:page().blocks){if(b.type.equals("Heading"))h.append("<div class=hero><h1>").append(esc(b.text)).append("</h1></div>");else if(b.type.equals("Text"))h.append("<p>").append(esc(b.text)).append("</p>");else if(b.type.equals("Button"))h.append("<a class=btn href=#>").append(esc(b.text)).append("</a>");else if(b.type.equals("Image"))h.append("<img class=image src=\"").append(imageData(b.imageUri)).append("\">");else if(b.type.equals("Section"))h.append("<section class=section><h2>").append(esc(b.text)).append("</h2></section>");else if(b.type.equals("Card"))h.append("<div class=card>").append(esc(b.text)).append("</div>");else if(b.type.equals("Navbar"))h.append("<nav class=nav>").append(esc(b.text)).append("</nav>");else if(b.type.equals("Footer"))h.append("<footer class=footer>").append(esc(b.text)).append("</footer>");}return h.append("</div></body></html>").toString();}
 void preview(){WebView w=new WebView(this);w.loadDataWithBaseURL(null,html(),"text/html","UTF-8",null);new AlertDialog.Builder(this).setTitle("Website Preview").setView(w).setPositiveButton("Close",null).show();}
 void settings(){new AlertDialog.Builder(this).setTitle("Settings").setItems(new String[]{"Save project","Reset current page","About"},(d,w)->{if(w==0)save();else if(w==1){page().blocks.clear();render();save();}else Toast.makeText(this,"Website Builder",Toast.LENGTH_SHORT).show();}).show();}
 void save(){SharedPreferences.Editor e=prefs.edit();e.putInt("pages",pages.size()).putInt("current",currentPage).putString("project",projectTitle==null?"My Website":projectTitle.getText().toString());for(int i=0;i<pages.size();i++){Page p=pages.get(i);e.putString("p"+i+"name",p.name).putInt("p"+i+"count",p.blocks.size());for(int j=0;j<p.blocks.size();j++){Block b=p.blocks.get(j);e.putString("p"+i+"b"+j+"t",b.type).putString("p"+i+"b"+j+"x",b.text).putString("p"+i+"b"+j+"u",b.imageUri);}}e.apply();if(status!=null)status.setText("Saved locally");}
 void load(){int n=prefs.getInt("pages",0);if(n==0){pages.add(new Page("Home"));return;}for(int i=0;i<n;i++){Page p=new Page(prefs.getString("p"+i+"name","Page "+(i+1)));int c=prefs.getInt("p"+i+"count",0);for(int j=0;j<c;j++)p.blocks.add(new Block(prefs.getString("p"+i+"b"+j+"t","Text"),prefs.getString("p"+i+"b"+j+"x",""),prefs.getString("p"+i+"b"+j+"u","")));pages.add(p);}currentPage=Math.min(prefs.getInt("current",0),pages.size()-1);}
}