package com.amb8657.websitebuilder;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.*;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.util.Base64;
import android.view.*;
import android.webkit.WebView;
import android.widget.*;
import java.util.*;

public class VisualBuilderActivity extends Activity {
 static final int BG=Color.rgb(19,18,23),SOFT=Color.rgb(31,30,36),TEXT=Color.rgb(237,235,243),DIM=Color.rgb(156,153,168),ACCENT=Color.rgb(124,92,255);
 LinearLayout root,canvasHost,pagesBar,toolsBar; SharedPreferences sp; ArrayList<Project> projects=new ArrayList<>(); Project project; Page page; Block selected; int imageIndex=-1;
 static class Project{String name;ArrayList<Page> pages=new ArrayList<>();Project(String n){name=n;}}
 static class Page{String name;int bg=Color.WHITE,text=Color.DKGRAY,accent=ACCENT;ArrayList<Block> blocks=new ArrayList<>();Page(String n){name=n;}}
 static class Block{String type,text,uri="",action="None",target="";int x=20,y=20,w=300,h=80,bg=0,tc=Color.DKGRAY,font=16;Block(String t,String s){type=t;text=s;}}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} GradientDrawable shape(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setMinHeight(0);b.setMinWidth(0);b.setBackground(shape(SOFT,9));return b;}
 TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(SOFT);getWindow().setNavigationBarColor(SOFT);sp=getSharedPreferences("visual_builder",0);loadList();showProjects();}
 String key(String n){return"v_"+Base64.encodeToString(n.getBytes(),Base64.NO_WRAP|Base64.URL_SAFE);}
 void loadList(){String s=sp.getString("projects","");if(!s.isEmpty())for(String n:s.split("\\|"))if(!n.isEmpty())projects.add(load(n));if(projects.isEmpty()){Project p=new Project("My Website");p.pages.add(new Page("Home"));projects.add(p);save(p);saveList();}}
 Project load(String n){Project p=new Project(n);String k=key(n);int pc=sp.getInt(k+"pc",0);if(pc==0){p.pages.add(new Page("Home"));return p;}for(int i=0;i<pc;i++){Page q=new Page(sp.getString(k+"pn"+i,"Page"+(i+1)));q.bg=sp.getInt(k+"bg"+i,Color.WHITE);q.text=sp.getInt(k+"tc"+i,Color.DKGRAY);q.accent=sp.getInt(k+"ac"+i,ACCENT);int bc=sp.getInt(k+"bc"+i,0);for(int j=0;j<bc;j++){String z=k+"b"+i+"_"+j;Block b=new Block(sp.getString(z+"t","Text"),sp.getString(z+"x",""));b.uri=sp.getString(z+"u","");b.action=sp.getString(z+"a","None");b.target=sp.getString(z+"g","");b.x=sp.getInt(z+"xpos",20);b.y=sp.getInt(z+"ypos",20);b.w=sp.getInt(z+"w",300);b.h=sp.getInt(z+"h",80);b.bg=sp.getInt(z+"bg",0);b.tc=sp.getInt(z+"tc",q.text);b.font=sp.getInt(z+"f",16);q.blocks.add(b);}p.pages.add(q);}return p;}
 void saveList(){StringBuilder s=new StringBuilder();for(Project p:projects){if(s.length()>0)s.append('|');s.append(p.name.replace("|"," "));}sp.edit().putString("projects",s.toString()).apply();}
 void save(Project p){String k=key(p.name);SharedPreferences.Editor e=sp.edit().putInt(k+"pc",p.pages.size());for(int i=0;i<p.pages.size();i++){Page q=p.pages.get(i);e.putString(k+"pn"+i,q.name).putInt(k+"bg"+i,q.bg).putInt(k+"tc"+i,q.text).putInt(k+"ac"+i,q.accent).putInt(k+"bc"+i,q.blocks.size());for(int j=0;j<q.blocks.size();j++){Block b=q.blocks.get(j);String z=k+"b"+i+"_"+j;e.putString(z+"t",b.type).putString(z+"x",b.text).putString(z+"u",b.uri).putString(z+"a",b.action).putString(z+"g",b.target).putInt(z+"xpos",b.x).putInt(z+"ypos",b.y).putInt(z+"w",b.w).putInt(z+"h",b.h).putInt(z+"bg",b.bg).putInt(z+"tc",b.tc).putInt(z+"f",b.font);}}e.apply();}
 void showProjects(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);TextView h=tv("P   Website Builder",22,TEXT);h.setTypeface(Typeface.DEFAULT_BOLD);h.setPadding(dp(18),0,0,0);root.addView(h,new LinearLayout.LayoutParams(-1,dp(82)));root.addView(tv("Projects",17,DIM),new LinearLayout.LayoutParams(-1,dp(42)));ScrollView sv=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(16),dp(8),dp(16),dp(24));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));Button n=btn("+  New Project");n.setTextSize(16);n.setTextColor(Color.WHITE);n.setBackground(shape(ACCENT,12));list.addView(n,new LinearLayout.LayoutParams(-1,dp(58)));n.setOnClickListener(v->newProject());for(Project p:projects){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(5),dp(6),dp(5));r.setBackground(shape(SOFT,12));TextView name=tv(p.name,16,TEXT);name.setTypeface(Typeface.DEFAULT_BOLD);r.addView(name,new LinearLayout.LayoutParams(0,dp(58),1));Button o=btn("Open");r.addView(o,new LinearLayout.LayoutParams(dp(72),dp(44)));list.addView(r,new LinearLayout.LayoutParams(-1,dp(70)));o.setOnClickListener(v->{project=p;page=p.pages.get(0);showEditor();});name.setOnClickListener(v->{project=p;page=p.pages.get(0);showEditor();});}}
 void newProject(){EditText e=new EditText(this);e.setHint("Project name");new AlertDialog.Builder(this).setTitle("New Project").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="My Website";Project p=new Project(n);p.pages.add(new Page("Home"));projects.add(0,p);save(p);saveList();project=p;page=p.pages.get(0);showEditor();}).show();}
 void showEditor(){root.removeAllViews();LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setBackgroundColor(BG);root.addView(top,new LinearLayout.LayoutParams(-1,dp(110)));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹");r.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));TextView title=tv(project.name,18,TEXT);title.setTypeface(Typeface.DEFAULT_BOLD);r.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));top.addView(r);back.setOnClickListener(v->{save(project);showProjects();});LinearLayout acts=new LinearLayout(this);Button code=btn("Code"),prev=btn("Preview"),exp=btn("Export");acts.addView(code,new LinearLayout.LayoutParams(0,dp(42),1));acts.addView(prev,new LinearLayout.LayoutParams(0,dp(42),1));exp.setTextColor(Color.WHITE);exp.setBackground(shape(ACCENT,8));acts.addView(exp,new LinearLayout.LayoutParams(0,dp(42),1));top.addView(acts);code.setOnClickListener(v->showCode());prev.setOnClickListener(v->preview());HorizontalScrollView ph=new HorizontalScrollView(this);pagesBar=new LinearLayout(this);pagesBar.setPadding(dp(8),dp(5),dp(8),dp(5));ph.addView(pagesBar);root.addView(ph,new LinearLayout.LayoutParams(-1,dp(52)));HorizontalScrollView th=new HorizontalScrollView(this);toolsBar=new LinearLayout(this);toolsBar.setPadding(dp(8),dp(5),dp(8),dp(5));th.addView(toolsBar);root.addView(th,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout main=new LinearLayout(this);main.setOrientation(LinearLayout.VERTICAL);root.addView(main,new LinearLayout.LayoutParams(-1,0,1));ScrollView sv=new ScrollView(this);canvasHost=new LinearLayout(this);canvasHost.setPadding(dp(10),dp(10),dp(10),dp(90));sv.addView(canvasHost);main.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bottom=new LinearLayout(this);bottom.setBackgroundColor(SOFT);Button pages=btn("Pages"),style=btn("Style"),saveb=btn("Save");bottom.addView(pages,new LinearLayout.LayoutParams(0,dp(58),1));bottom.addView(style,new LinearLayout.LayoutParams(0,dp(58),1));bottom.addView(saveb,new LinearLayout.LayoutParams(0,dp(58),1));root.addView(bottom);pages.setOnClickListener(v->pageDialog());style.setOnClickListener(v->styleDialog());saveb.setOnClickListener(v->{save(project);Toast.makeText(this,"Saved",Toast.LENGTH_SHORT).show();});render();}
 void render(){pagesBar.removeAllViews();for(Page p:project.pages){Button b=btn(p.name);if(p==page)b.setBackground(shape(Color.rgb(45,34,70),8));b.setOnClickListener(v->{page=p;selected=null;render();});pagesBar.addView(b,new LinearLayout.LayoutParams(dp(105),dp(40)));}Button np=btn("+ New");np.setOnClickListener(v->newPage());pagesBar.addView(np,new LinearLayout.LayoutParams(dp(80),dp(40)));toolsBar.removeAllViews();for(String s:new String[]{"Heading","Text","Image","Button","Section","Spacer"}){Button b=btn("+ "+s);b.setOnClickListener(v->addBlock(s));toolsBar.addView(b,new LinearLayout.LayoutParams(dp(100),dp(38)));}canvasHost.removeAllViews();FrameLayout canvas=new FrameLayout(this);canvas.setBackgroundColor(page.bg);canvas.setMinimumHeight(dp(650));canvasHost.addView(canvas,new LinearLayout.LayoutParams(-1,dp(650)));for(int i=0;i<page.blocks.size();i++)putBlock(canvas,page.blocks.get(i));}
 void putBlock(FrameLayout canvas,Block b){FrameLayout holder=new FrameLayout(this);holder.setX(dp(b.x));holder.setY(dp(b.y));boolean isSelected=selected==b;GradientDrawable selection=new GradientDrawable();selection.setColor(Color.TRANSPARENT);selection.setCornerRadius(dp(8));if(isSelected)selection.setStroke(dp(2),ACCENT);holder.setBackground(selection);View v;if(b.type.equals("Image")&&!b.uri.isEmpty()){ImageView im=new ImageView(this);im.setImageURI(Uri.parse(b.uri));im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);v=im;}else{TextView t=tv(b.text,b.font,b.tc);t.setGravity(b.type.equals("Button")?Gravity.CENTER:Gravity.CENTER_VERTICAL);t.setPadding(dp(8),dp(5),dp(8),dp(5));if(b.type.equals("Heading"))t.setTypeface(Typeface.DEFAULT_BOLD);if(b.type.equals("Button")){t.setTextColor(Color.WHITE);t.setBackground(shape(b.bg==0?page.accent:b.bg,8));}if(b.type.equals("Section")){t.setText("");t.setBackground(shape(b.bg==0?Color.TRANSPARENT:b.bg,8));}v=t;}holder.addView(v,new FrameLayout.LayoutParams(-1,-1));TextView handle=tv("↘",12,isSelected?ACCENT:Color.TRANSPARENT);handle.setGravity(Gravity.CENTER);FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(dp(30),dp(30),Gravity.RIGHT|Gravity.BOTTOM);holder.addView(handle,hp);FrameLayout.LayoutParams size=new FrameLayout.LayoutParams(dp(Math.max(80,b.w)),dp(Math.max(45,b.h)));canvas.addView(holder,size);holder.setOnClickListener(x->{selected=b;render();properties(b);});handle.setOnTouchListener((x,e)->resizeTouch(e,holder,b));holder.setOnLongClickListener(x->{dragTouch(holder,b);return true;});}
 boolean resizeTouch(MotionEvent e,View v,Block b){if(e.getAction()==MotionEvent.ACTION_DOWN){final float sx=e.getRawX(),sy=e.getRawY();final int sw=b.w,sh=b.h;v.setTag(new float[]{sx,sy,sw,sh});return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float[] a=(float[])v.getTag();float d=(e.getRawX()-a[0])/getResources().getDisplayMetrics().density;float q=(e.getRawY()-a[1])/getResources().getDisplayMetrics().density;b.w=Math.max(80,(int)(a[2]+d));b.h=Math.max(45,(int)(a[3]+q));v.getLayoutParams().width=dp(b.w);v.getLayoutParams().height=dp(b.h);v.requestLayout();return true;}if(e.getAction()==MotionEvent.ACTION_UP){save(project);return true;}return true;}
 void dragTouch(View v,Block b){v.setOnTouchListener(new View.OnTouchListener(){float dx,dy;public boolean onTouch(View x,MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){dx=e.getRawX()-v.getX();dy=e.getRawY()-v.getY();return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float den=getResources().getDisplayMetrics().density;b.x=Math.max(0,(int)((e.getRawX()-dx)/den));b.y=Math.max(0,(int)((e.getRawY()-dy)/den));v.setX(dp(b.x));v.setY(dp(b.y));return true;}if(e.getAction()==MotionEvent.ACTION_UP){save(project);v.setOnTouchListener(null);return true;}return true;}});}
 void addBlock(String type){Block b=new Block(type,type.equals("Heading")?"Your Heading Here":type.equals("Text")?"Write your text here.":type.equals("Button")?"Click Me":type.equals("Section")?"":"Image");b.y=20;for(Block q:page.blocks)b.y=Math.max(b.y,q.y+q.h+20);b.w=300;b.h=type.equals("Image")?180:type.equals("Heading")?85:type.equals("Section")?160:80;page.blocks.add(b);selected=b;save(project);render();if(type.equals("Image"))pickImage(b);else properties(b);}
 EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(TEXT);return e;}
 int val(EditText e,int f){try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception x){return f;}}
 int col(String s,int f){try{return Color.parseColor(s.trim());}catch(Exception x){return f;}}
 String hex(int c){return String.format(Locale.US,"#%06X",0xFFFFFF&c);}
 void properties(Block b){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),dp(8));box.addView(tv(b.type+" Properties",17,TEXT),new LinearLayout.LayoutParams(-1,dp(42)));EditText text=field("Text",b.text);box.addView(text,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout sz=new LinearLayout(this);EditText w=field("Width",String.valueOf(b.w)),h=field("Height",String.valueOf(b.h));sz.addView(w,new LinearLayout.LayoutParams(0,dp(48),1));sz.addView(h,new LinearLayout.LayoutParams(0,dp(48),1));box.addView(sz);LinearLayout pos=new LinearLayout(this);EditText x=field("X",String.valueOf(b.x)),y=field("Y",String.valueOf(b.y));pos.addView(x,new LinearLayout.LayoutParams(0,dp(48),1));pos.addView(y,new LinearLayout.LayoutParams(0,dp(48),1));box.addView(pos);EditText color=field("Colour",hex(b.bg==0?page.accent:b.bg));box.addView(color,new LinearLayout.LayoutParams(-1,dp(50)));if(b.type.equals("Button")){Button act=btn("Button destination / action");box.addView(act,new LinearLayout.LayoutParams(-1,dp(46)));act.setOnClickListener(v->buttonDialog(b));}if(b.type.equals("Image")){Button img=btn("Choose / replace image");box.addView(img,new LinearLayout.LayoutParams(-1,dp(46)));img.setOnClickListener(v->pickImage(b));}LinearLayout r=new LinearLayout(this);Button del=btn("Delete"),close=btn("Close"),apply=btn("Apply");r.addView(del,new LinearLayout.LayoutParams(0,dp(44),1));r.addView(close,new LinearLayout.LayoutParams(0,dp(44),1));r.addView(apply,new LinearLayout.LayoutParams(0,dp(44),1));box.addView(r);Dialog d=new Dialog(this);d.setContentView(box);del.setOnClickListener(v->{page.blocks.remove(b);selected=null;save(project);d.dismiss();render();});close.setOnClickListener(v->d.dismiss());apply.setOnClickListener(v->{b.text=text.getText().toString();b.w=Math.max(80,val(w,b.w));b.h=Math.max(45,val(h,b.h));b.x=Math.max(0,val(x,b.x));b.y=Math.max(0,val(y,b.y));b.bg=col(color.getText().toString(),b.bg);save(project);d.dismiss();render();});d.show();Window z=d.getWindow();if(z!=null)z.setLayout(-1,-2);}
 void buttonDialog(Block b){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Spinner s=new Spinner(this);String[] a={"None","Open another page","Open website","Email","Phone","Scroll to section"};s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));box.addView(s,new LinearLayout.LayoutParams(-1,dp(52)));EditText target=field("Destination",b.target);box.addView(target,new LinearLayout.LayoutParams(-1,dp(54)));new AlertDialog.Builder(this).setTitle("Button destination").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{b.action=s.getSelectedItem().toString();b.target=target.getText().toString();save(project);}).show();}
 void styleDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText bg=field("Background",hex(page.bg)),tc=field("Text",hex(page.text)),ac=field("Accent / Buttons",hex(page.accent));box.addView(bg);box.addView(tc);box.addView(ac);new AlertDialog.Builder(this).setTitle("Style — no code needed").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{page.bg=col(bg.getText().toString(),page.bg);page.text=col(tc.getText().toString(),page.text);page.accent=col(ac.getText().toString(),page.accent);save(project);render();}).show();}
 void newPage(){EditText e=new EditText(this);e.setHint("Page name");new AlertDialog.Builder(this).setTitle("New page").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Create",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="New Page";page=new Page(n);project.pages.add(page);save(project);render();}).show();}
 void pageDialog(){String[] a=new String[project.pages.size()+1];for(int i=0;i<project.pages.size();i++)a[i]=project.pages.get(i).name;a[project.pages.size()]= "+ New page";new AlertDialog.Builder(this).setTitle("Pages").setItems(a,(d,w)->{if(w<project.pages.size()){page=project.pages.get(w);render();}else newPage();}).show();}
 void pickImage(Block b){imageIndex=page.blocks.indexOf(b);Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,401);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==401&&c==RESULT_OK&&d!=null&&imageIndex>=0){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}Block b=page.blocks.get(imageIndex);b.uri=u.toString();b.text=fileName(u);save(project);render();}}
 String fileName(Uri u){Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){try{int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)return c.getString(i);}finally{c.close();}}return"image";}
 void preview(){WebView w=new WebView(this);w.loadDataWithBaseURL(null,html(page),"text/html","UTF-8",null);Dialog d=new Dialog(this);d.setContentView(w);d.show();Window z=d.getWindow();if(z!=null)z.setLayout(-1,-1);}
 String html(Page p){StringBuilder s=new StringBuilder("<html><meta name=viewport content=width=device-width><body style='margin:0;background:"+hex(p.bg)+";color:"+hex(p.text)+"'><div style='position:relative;min-height:100vh'>");for(Block b:p.blocks){String st="position:absolute;left:"+b.x+"px;top:"+b.y+"px;width:"+b.w+"px;height:"+b.h+"px;box-sizing:border-box;";if(b.type.equals("Image")&&!b.uri.isEmpty())s.append("<img src='").append(b.uri).append("' style='").append(st).append("object-fit:contain'>");else if(b.type.equals("Button"))s.append("<a href='").append(b.target).append("' style='").append(st).append("display:flex;align-items:center;justify-content:center;background:").append(hex(b.bg==0?p.accent:b.bg)).append(";color:white;text-decoration:none;border-radius:8px'>").append(esc(b.text)).append("</a>");else s.append("<div style='").append(st).append("font-size:").append(b.font).append("px'>").append(esc(b.text)).append("</div>");}return s.append("</div></body></html>").toString();}
 String esc(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 void showCode(){EditText e=field("",html(page));e.setGravity(Gravity.TOP);new AlertDialog.Builder(this).setTitle("Advanced code").setView(e).setPositiveButton("Close",null).show();}
}
