package com.amb8657.websitebuilder;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import java.util.*;

public class WebsiteBuilderV4Activity extends Activity {
    final int BG=CanvaDesignSystem.BG,PANEL=CanvaDesignSystem.PANEL,PANEL2=CanvaDesignSystem.PANEL_2,ACCENT=CanvaDesignSystem.ACCENT,WHITE=Color.WHITE,MUTED=CanvaDesignSystem.MUTED;
    LinearLayout root,tools,inspector,pages; FrameLayout canvas; ScrollView scroll; ArrayList<Item> items=new ArrayList<>(); int next=1; Item selected; int pageBg=Color.WHITE;
    static class Item {int id,x=80,y=80,w=300,h=80,color=0x00000000,textColor=Color.DKGRAY,font=18,radius=0;String type,text="",action="None",target="",animation="None",uri="";boolean crop;Item(int i,String t,String s){id=i;type=t;text=s;}}
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setMinHeight(0);x.setMinWidth(0);x.setTextSize(13);x.setBackground(bg(Color.WHITE,9));return x;}
    @Override public void onCreate(Bundle x){super.onCreate(x);showSplash();}
    void showSplash(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setBackgroundColor(BG);setContentView(root);ImageView i=new ImageView(this);i.setImageResource(com.amb8657.websitebuilder.R.drawable.gmail);i.setBackground(bg(Color.WHITE,28));i.setPadding(dp(18),dp(18),dp(18),dp(18));root.addView(i,new LinearLayout.LayoutParams(dp(112),dp(112)));TextView t=tv("Website Builder",25,WHITE);t.setGravity(Gravity.CENTER);root.addView(t,new LinearLayout.LayoutParams(-1,dp(58)));TextView s=tv("Create  •  Design  •  Publish",14,MUTED);s.setGravity(Gravity.CENTER);root.addView(s,new LinearLayout.LayoutParams(-1,dp(34)));new Handler().postDelayed(this::editor,1800);}
    void editor(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);
        LinearLayout top=row();Button back=b("‹"),undo=b("↶"),redo=b("↷"),preview=b("Preview"),publish=b("Publish");top.addView(back,new LinearLayout.LayoutParams(dp(42),dp(46)));TextView title=tv("Website Builder",17,WHITE);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,dp(46),1));top.addView(undo,new LinearLayout.LayoutParams(dp(42),dp(44)));top.addView(redo,new LinearLayout.LayoutParams(dp(42),dp(44)));top.addView(preview,new LinearLayout.LayoutParams(dp(78),dp(44)));publish.setTextColor(WHITE);publish.setBackground(bg(ACCENT,9));top.addView(publish,new LinearLayout.LayoutParams(dp(78),dp(44)));root.addView(top,new LinearLayout.LayoutParams(-1,dp(58)));preview.setOnClickListener(v->preview());publish.setOnClickListener(v->preview());
        HorizontalScrollView p=new HorizontalScrollView(this);pages=new LinearLayout(this);p.addView(pages);root.addView(p,new LinearLayout.LayoutParams(-1,dp(48)));HorizontalScrollView tt=new HorizontalScrollView(this);tools=new LinearLayout(this);tt.addView(tools);root.addView(tt,new LinearLayout.LayoutParams(-1,dp(50)));
        LinearLayout body=row();scroll=new ScrollView(this);canvas=new FrameLayout(this);canvas.setBackgroundColor(pageBg);scroll.addView(canvas,new ScrollView.LayoutParams(dp(1366),dp(900)));body.addView(scroll,new LinearLayout.LayoutParams(0,0,1));ScrollView ins=new ScrollView(this);inspector=new LinearLayout(this);inspector.setOrientation(LinearLayout.VERTICAL);inspector.setPadding(dp(8),dp(8),dp(8),dp(8));inspector.setBackgroundColor(PANEL);ins.addView(inspector);body.addView(ins,new LinearLayout.LayoutParams(dp(290),0));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout bottom=row();Button pg=b("Pages"),sty=b("Style"),pv=b("Preview");bottom.setBackgroundColor(PANEL);bottom.addView(pg,new LinearLayout.LayoutParams(0,dp(58),1));bottom.addView(sty,new LinearLayout.LayoutParams(0,dp(58),1));bottom.addView(pv,new LinearLayout.LayoutParams(0,dp(58),1));root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(62)));sty.setOnClickListener(v->palette());pv.setOnClickListener(v->preview());pg.setOnClickListener(v->Toast.makeText(this,"Pages: Home",Toast.LENGTH_SHORT).show());back.setOnClickListener(v->showSplash());buildTools();render();}
    LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    void buildTools(){for(String n:new String[]{"Text","Image","Button","Section","Shape","Tool"}){Button x=b("＋ "+n);tools.addView(x,new LinearLayout.LayoutParams(dp(92),dp(40)));x.setOnClickListener(v->add(n));}}
    void add(String type){Item i=new Item(next++,type,"Text".equals(type)?"Your text":"Button".equals(type)?"Button":"");i.x=80+items.size()*10;i.y=80+items.size()*10;if("Section".equals(type)){i.w=700;i.h=180;i.color=0xFFECEFF5;}if("Shape".equals(type)){i.w=240;i.h=140;i.color=0xFFECEFF5;}if("Button".equals(type))i.color=ACCENT;if("Image".equals(type)){imageTarget=i;pickImage();return;}items.add(i);selected=i;render();}
    void render(){canvas.removeAllViews();for(Item i:items)draw(i);showInspector();}
    void draw(Item i){FrameLayout h=new FrameLayout(this);h.setX(dp(i.x));h.setY(dp(i.y));h.setBackground(bg(i.color,i.radius));TextView t=tv(i.text,i.font,i.textColor);t.setPadding(dp(8),dp(4),dp(8),dp(4));if("Button".equals(i.type)||"Tool".equals(i.type))t.setGravity(Gravity.CENTER);h.addView(t,new FrameLayout.LayoutParams(-1,-1));if(selected==i){GradientDrawable g=bg(i.color,i.radius);g.setStroke(dp(2),ACCENT);h.setBackground(g);moveHandle(h,i);resizeHandle(h,i);}h.setOnTouchListener((v,e)->move(h,e,i));canvas.addView(h,new FrameLayout.LayoutParams(dp(Math.max(60,i.w)),dp(Math.max(40,i.h))));}
    void moveHandle(FrameLayout h,Item i){TextView m=tv("↕",15,ACCENT);m.setGravity(Gravity.CENTER);m.setBackground(bg(WHITE,12));FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(dp(32),dp(28),Gravity.TOP|Gravity.CENTER_HORIZONTAL);p.topMargin=-dp(34);h.addView(m,p);m.setOnTouchListener((v,e)->move(h,e,i));}
    void resizeHandle(FrameLayout h,Item i){TextView r=tv("",1,ACCENT);r.setBackground(bg(WHITE,8));h.addView(r,new FrameLayout.LayoutParams(dp(18),dp(18),Gravity.RIGHT|Gravity.BOTTOM));r.setOnTouchListener((v,e)->resize(h,e,i));}
    boolean move(View v,MotionEvent e,Item i){if(e.getAction()==0){selected=i;v.setTag(new float[]{e.getRawX(),e.getRawY(),i.x,i.y});v.getParent().requestDisallowInterceptTouchEvent(true);showInspector();return true;}if(e.getAction()==2){float[] a=(float[])v.getTag();i.x=Math.max(0,(int)(a[2]+(e.getRawX()-a[0])/getResources().getDisplayMetrics().density));i.y=Math.max(0,(int)(a[3]+(e.getRawY()-a[1])/getResources().getDisplayMetrics().density));v.setX(dp(i.x));v.setY(dp(i.y));return true;}if(e.getAction()==1){v.getParent().requestDisallowInterceptTouchEvent(false);render();}return true;}
    boolean resize(View v,MotionEvent e,Item i){if(e.getAction()==0){v.setTag(new float[]{e.getRawX(),e.getRawY(),i.w,i.h});v.getParent().requestDisallowInterceptTouchEvent(true);return true;}if(e.getAction()==2){float[] a=(float[])v.getTag();i.w=Math.max(60,(int)(a[2]+(e.getRawX()-a[0])/getResources().getDisplayMetrics().density));i.h=Math.max(40,(int)(a[3]+(e.getRawY()-a[1])/getResources().getDisplayMetrics().density));v.getParent().getLayoutParams().width=dp(i.w);v.getParent().getLayoutParams().height=dp(i.h);v.getParent().requestLayout();return true;}if(e.getAction()==1){v.getParent().requestDisallowInterceptTouchEvent(false);render();}return true;}
    Item imageTarget; void pickImage(){Intent q=new Intent(Intent.ACTION_OPEN_DOCUMENT);q.setType("image/*");q.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(q,701);} @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==701&&c==RESULT_OK&&d!=null&&d.getData()!=null&&imageTarget!=null){imageTarget.uri=d.getData().toString();try{getContentResolver().takePersistableUriPermission(d.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}items.add(imageTarget);selected=imageTarget;imageTarget=null;render();}}
    void showInspector(){inspector.removeAllViews();if(selected==null){inspector.addView(tv("Select an element",17,WHITE));return;}inspector.addView(tv(selected.type+" properties",18,WHITE));if("Text".equals(selected.type)||"Button".equals(selected.type)||"Tool".equals(selected.type)){EditText e=new EditText(this);e.setText(selected.text);e.setTextColor(WHITE);inspector.addView(e,new LinearLayout.LayoutParams(-1,dp(44)));e.setOnFocusChangeListener((v,f)->{if(!f){selected.text=e.getText().toString();render();}});Button c=b("Text colour");inspector.addView(c);c.setOnClickListener(v->paletteText());}if("Button".equals(selected.type)){Button bc=b("Button colour");inspector.addView(bc);bc.setOnClickListener(v->paletteFill());Button a=b("Action: "+selected.action);inspector.addView(a);a.setOnClickListener(v->action());}if("Image".equals(selected.type)){Button crop=b("Crop: "+selected.crop);inspector.addView(crop);crop.setOnClickListener(v->{selected.crop=!selected.crop;render();});Button r=b("Corner radius: drag handle");inspector.addView(r);}if("Section".equals(selected.type)||"Shape".equals(selected.type)){Button f=b("Fill colour");inspector.addView(f);f.setOnClickListener(v->paletteFill());Button inside=b("Add element inside");inspector.addView(inside);inside.setOnClickListener(v->Toast.makeText(this,"Select an element tool, then place it inside the section/shape",Toast.LENGTH_SHORT).show());}Button an=b("Animation: "+selected.animation);inspector.addView(an);an.setOnClickListener(v->animation());Button del=b("Delete");del.setTextColor(Color.rgb(220,70,80));inspector.addView(del);del.setOnClickListener(v->{items.remove(selected);selected=null;render();});}
    void paletteText(){paletteDialog(true);}void paletteFill(){paletteDialog(false);}void palette(){paletteDialog(selected!=null&&"Text".equals(selected.type));}
    void paletteDialog(boolean text){String[] labels={"Recent","Project","Neutral","Primary","Secondary","Accent","Custom HEX"};int[] colors={Color.WHITE,Color.BLACK,0xFFF5F6FA,ACCENT,PURPLE,0xFF20A07D,0xFFEB5757,0xFFF2994A,0xFF2F80ED};LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);for(int n:colors){Button s=b("     ");s.setBackground(bg(n,7));box.addView(s,new LinearLayout.LayoutParams(-1,dp(34)));s.setOnClickListener(v->{if(selected!=null){if(text)selected.textColor=n;else selected.color=n;render();}});}EditText hex=new EditText(this);hex.setHint("#RRGGBB");box.addView(hex,new LinearLayout.LayoutParams(-1,dp(44)));new AlertDialog.Builder(this).setTitle("Colour palette").setView(box).setPositiveButton("Apply",(d,w)->{try{int c=Color.parseColor(hex.getText().toString());if(selected!=null){if(text)selected.textColor=c;else selected.color=c;render();}}catch(Exception ignored){}}).setNegativeButton("Cancel",null).show();}
    void action(){String[] a={"None","Open URL","Open page"};new AlertDialog.Builder(this).setTitle("Button action").setItems(a,(d,w)->{selected.action=a[w];if(w>0){EditText e=new EditText(this);e.setText(selected.target);new AlertDialog.Builder(this).setTitle("Destination").setView(e).setPositiveButton("Save",(x,y)->{selected.target=e.getText().toString();render();}).setNegativeButton("Cancel",null).show();}else render();});}
    void animation(){String[] a={"None","Fade In","Slide Up","Slide Left","Scale In"};new AlertDialog.Builder(this).setTitle("Animation / interaction").setItems(a,(d,w)->{selected.animation=a[w];render();});}
    void preview(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(pageBg);setContentView(r);LinearLayout bar=row();TextView t=tv("Preview",18,WHITE);bar.addView(t,new LinearLayout.LayoutParams(0,dp(52),1));Button edit=b("Edit");bar.addView(edit);r.addView(bar,new LinearLayout.LayoutParams(-1,dp(58)));ScrollView s=new ScrollView(this);FrameLayout c=new FrameLayout(this);c.setBackgroundColor(pageBg);s.addView(c,new ScrollView.LayoutParams(dp(1366),dp(900)));r.addView(s,new LinearLayout.LayoutParams(-1,0,1));for(Item i:items){FrameLayout h=new FrameLayout(this);h.setX(dp(i.x));h.setY(dp(i.y));h.setBackground(bg(i.color,i.radius));TextView x=tv(i.text,i.font,i.textColor);x.setGravity("Button".equals(i.type)?Gravity.CENTER:Gravity.CENTER_VERTICAL);h.addView(x,new FrameLayout.LayoutParams(dp(i.w),dp(i.h)));if("Button".equals(i.type))h.setOnClickListener(v->{if("Open URL".equals(i.action)&&!i.target.isEmpty())startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(i.target)));});c.addView(h);}edit.setOnClickListener(v->editor());}
}
